### ISSUE TITLE
Disconnect when switching to full screen on Windows

### ISSUE THREAD

**Issue by noamgat** [GoogleCloudPlatform/iap-desktop#1005]
Hi,
We have several Windows VMs on GCP. IAP Desktop App works great, except for one problem. If we try to switch to full screen (right click on tab -> Full Screen), we get disconnected from the server. Is this a known issue? Are there known workarounds?

**Comment by jpassing** [comment]
That is indeed a known issue and #245 has some more details. The disconnects are caused by the Windows Remote Desktop ActiveX control and I'm currently not aware of any way to prevent this (somewhat annoying) behavior.

**Comment by jpassing** [comment]
This is going to be fixed in the upcoming release. As it turns out, it is possible to do full-screen switching without a reconnect, at least in most circumstances.

**Comment by jpassing** [comment]
This [is now fixed in version 2.40](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.40.1418), so I'll close this issue.
