### ISSUE TITLE
forcefully closed connection: Connection reset

### ISSUE THREAD

**Issue by atlpitch** [GoogleCloudPlatform/iap-desktop#1029]
Hi forgive me if this has been reported elsewhere, I didn't see it. IAP Desktop was working fine for all users until recently and now after connecting and sending packets for a bit the connection is forcibly closed and the session is disconnected. I included a portion of the logs below before, during and after the disconnect. Any suggestions on how to troubleshoot this? We haven't made changes on the server end but it appears that the disconnect is being closed there. Any help would be appreciated.

Google.Solutions.IapTunneling Verbose: 0 : NetworkStream [[SshRelaySession AbvJZZ6XU1 AR: 3258 AS: 2820 TR: 3084 TX: 3258] > [Socket xxx.xxx.xxx.xxx:63846]]: Reading...
Google.Solutions.IapTunneling Verbose: 0 : WebSocketStream: begin ReadAsync()... [socket: Open]
Google.Solutions.IapTunneling Verbose: 0 : WebSocketStream: end ReadAsync() - 44 bytes read [socket: Open]
Google.Solutions.IapTunneling Verbose: 0 : [SshRelaySession AbvJZZ6XU1 AR: 3258 AS: 2820 TR: 3084 TX: 3258]: Received DATA message (38 bytes)
Google.Solutions.IapTunneling Verbose: 0 : NetworkStream [[SshRelaySession AbvJZZ6XU1 AR: 3258 AS: 2820 TR: 3122 TX: 3258] > [Socket xxx.xxx.xxx.xxx:63846]]: Relaying 38 bytes
Google.Solutions.IapTunneling Verbose: 0 : NetworkStream [[SshRelaySession AbvJZZ6XU1 AR: 3258 AS: 2820 TR: 3122 TX: 3258] > [Socket xxx.xxx.xxx.xxx:63846]]: Reading...
Google.Solutions.IapTunneling Verbose: 0 : WebSocketStream: begin ReadAsync()... [socket: Open]
**Google.Solutions.IapTunneling Warning: 0 : NetworkStream [[Socket xxx.xxx.xxx.xxx:63846] > [SshRelaySession AbvJZZ6XU1 AR: 3258 AS: 2820 TR: 3122 TX: 3258]]: forcefully closed connection: Connection reset
Google.Solutions.IapTunneling Verbose: 0 : [SshRelaySession AbvJZZ6XU1 AR: 3258 AS: 2820 TR: 3122 TX: 3258]: Disconnected
Google.Solutions.IapTunneling Warning: 0 : NetworkStream [[SshRelaySession AbvJZZ6XU1 AR: 3258 AS: 2820 TR: 3122 TX: 3258] > [Socket xxx.xxx.xxx.xxx:63846]]: Caught unhandled exception: The semaphore has been disposed.    at System.Threading.SemaphoreSlim.CheckDispose()**
   at System.Threading.SemaphoreSlim.Release(Int32 releaseCount)
   at Google.Solutions.IapTunneling.Net.SingleReaderSingleWriterStream.<ReadAsyncWithCloseProtection>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Solutions.IapTunneling.Net.OneTimeUseStream.<ReadAsync>d__6.MoveNext()

**Comment by atlpitch** [comment]
Also, for what it's worth I did try your suggestion else where to try opening a tunnel using the gcloud cil on my mac and then using RDP to connect to the localhost and I can verify it works. So the server and RDP work there. This is specific to the IAP desktop app connection / settings,

**Comment by jpassing** [comment]
Thank you for sharing the logs. Interestingly, it's not IAP (i.e., the server-side) that's resetting the connection -- instead, it's the connection between the RDP control and the relay that's being reset (red arrow):

![image](https://github.com/GoogleCloudPlatform/iap-desktop/assets/5724941/fe440f29-4199-46ea-aa66-8368aca9b790)

That would suggest that the RDP control itself is terminating the connection for some reason.

How does the issue manifest itself in the UI? Does this happen after you already see the VM's desktop? Or does it happen earlier than that? And is there an error message that's displayed?

Have you seen the same issue with SSH? Or does this only happen with RDP?

> Also, for what it's worth I did try your suggestion else where to try opening a tunnel using the gcloud cil on my mac

If the error has something to do with the Windows RDP control, then it makes sense that the issue isn't reproducible on a Mac. 
Do you have `gcloud` installed on the Windows machine, and if so, would it be possible to repeat the test there?

**Comment by jpassing** [comment]
Closing this issue as I haven't heard back. Please reopen the issue if the problem persists or reappears.
