### ISSUE TITLE
SSMS integration

### ISSUE THREAD

**Issue by simonb-db** [GoogleCloudPlatform/iap-desktop#1071]
Liking the new integration of SSMS into IAP Desktop.  Makes it a lot easier to connect to my database instances from my desktop.  Liking, not loving... Yet.

1. When I create a connection, I have no way of seeing which instance I'm connected to, and most importantly, which _environment_ I'm connected to (Prod, Test, Stage, etc).  It just uses standard host, with a random port number.  Can this be configured somehow to open the tunnel with a specific port number defined in settings?  Or, better still, can it import the machine name, so it can be mapped to a matching hosts file entry, allowing use of the machine name in the SSMS object explorer?  
2. Being able to define the "connection settings" for a machine within IAP to use within SSMS would be great, so "Encrypt Connection", "Trust Server Cert" and especially "Use Custom Color".
3. Opening up a new SSMS application for each connection is a bit tiresome.  Would be great if it checked to see if an existing application was already open before spawning a new one.  Or, maybe there's a reason for this behaviour?

Think that's it for now - great work on something I hadn't realised I didn't have (having to RDP to each server is a chore).

Simon

**Comment by jpassing** [comment]
Thanks for sharing this feedback!

> It just uses standard host, with a random port number. 

The port numbers look random, but they aren't entirely: IAP Desktop [tries to use the same port number every time it connects to the same VM](https://github.com/GoogleCloudPlatform/iap-desktop/blob/master/sources/Google.Solutions.IapDesktop.Core/ClientModel/Transport/IapTunnel.cs#L326). The idea is that using the same port helps prevent "polluting" the connection history in client applications and lets them save credentials or connection settings. 

Unfortunately, that doesn't work too well with SSMS: When you change connection settings in SSMS (under  _Registered Servers_), SSMS won't apply them the next time -- even if the port number stays the same.

> Can this be configured somehow to open the tunnel with a specific port number defined in settings? Or, better still, can it import the machine name, so it can be mapped to a matching hosts file entry, allowing use of the machine name in the SSMS object explorer?

I agree that this would be useful. But the [SSMS command line options](https://learn.microsoft.com/en-us/sql/ssms/ssms-utility?view=sql-server-ver16) are pretty limited and don't allow for passing any extra settings... so I'm currently not sure how this could be done.

> Opening up a new SSMS application for each connection is a bit tiresome. 

One constraint here are Windows credentials: IAP Desktop lets you configure different Windows credentials for each VM, but each SSMS instance can only use one credential. So sharing a single SSMS instance across multiple connections would only work if all connections use the same credential.

Another constraint is, once again, the limited SSMS command line interface: There doesn't seem to be a way to tell SSMS "please open this connection in an existing instance".

For the next release, the plan is to add a feature that lets you open tunnels without launching an application (see #936). That might help to some extent: After you launched the first instance of SSMS, you could use that to add additional connections.

**Comment by jpassing** [comment]
[This comment on Stackoverflow](https://stackoverflow.com/questions/5294721/how-to-specify-a-port-number-in-sql-server-connection-string#comment5970088_5294741) is interesting:

>  instance name is ignored when port is specified. So "mycomputer.test.xxx.com\AnyOldRubbish,1234" ...

I gave it a try and it worked (using _Foobar_ as pseudo-instance name):

![image](https://github.com/GoogleCloudPlatform/iap-desktop/assets/5724941/8ae9e9a5-7fd1-4cc7-9f54-6607df8f4daa)

Assuming this works reliably, we could let IAP Desktop "inject" the VM name here.

**Comment by jpassing** [comment]
[Release 2.38](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.38.1281) now includes 2 changes that I hope will address your usage concerns:

1.  When you launch SSMS, Object Explorer now shows the instance name:

    ![image](https://github.com/GoogleCloudPlatform/iap-desktop/assets/5724941/beb22571-730e-4593-ace9-1e632d0fc32a)

3.  Instead of letting IAP Desktop launch SSMS, you can now forward a port, and connect to it manually from within SSMS:

    ![image](https://github.com/GoogleCloudPlatform/iap-desktop/assets/5724941/25646196-101e-495f-9f2a-c126a3ca4742)
