### ISSUE TITLE
Iap Desktop for Mac os clients 

### ISSUE THREAD

**Issue by i-baptgit** [GoogleCloudPlatform/iap-desktop#1073]
Hi,

Iap desktop for Mac os clients it is always on the roadmap for the future ?
The connection in gcloud is not very easy for basic users.

Thank's !

**Comment by jpassing** [comment]
Sorry, but there are currently no plans for a Mac version of IAP Desktop. That might change in the future, but at least for now the focus is on Windows only.

There's another open issue for Mac OS support (#554), so I'll close this one.
