### ISSUE TITLE
Feature request: oslogin with workforce identity

### ISSUE THREAD

**Issue by igpix** [GoogleCloudPlatform/iap-desktop#1158]
Hello team, 
It would be great to have the oslogin feature available for workforce identity user.

This error appears when connecting to a Linux vm
![image](https://github.com/GoogleCloudPlatform/iap-desktop/assets/63721210/6f0ef41a-6710-40d0-a542-a873b9463148)

oslogin works when connecting via gcloud

**Comment by jpassing** [comment]
I agree, and this is a high-priority feature on the roadmap.

When version 2.38 was released, OS Login didn't support workforce identity yet, but support for was just released [2 weeks ago](https://cloud.google.com/compute/docs/release-notes#October_13_2023).

**Comment by jpassing** [comment]
[Here's a preview build of IAP Desktop 2.39](https://issuetracker.google.com/action/issues/311436717/attachments/48764507?download=true) that supports OS Login with workforce identity, If you have the opportunity, it would be great if you could give that a try.

Two things to note:
1. You might need to update the guest environment on your VMs. OS Login with workforce identity federation uses SSH certificates, and support for that was only [added recently](https://github.com/GoogleCloudPlatform/guest-agent/releases/tag/stable).
4. To log in, you need to have the _Service Usage Consumer_ role on the project (in addition to the typical OS Login roles). This role is required for quota-charging purposes. 
   (This requirement might go away in the future.)

**Comment by jpassing** [comment]
This feature [is now available in version 2.39](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.39.1348), so I'm closing this issue.

**Comment by igpix** [comment]
@jpassing thank you for this improvement! I will check it as soon as possible
