### ISSUE TITLE
Provide a way to change the default profile.

### ISSUE THREAD

**Issue by pjmlp** [GoogleCloudPlatform/iap-desktop#1160]
After going through all the options and available documention, it seems that the only way to work around having a default profile with outdated configuration is to make use of the command line arguments to specify an alternate start profile.

I failed to find anything related how to define another profile as the default one.

**Comment by jpassing** [comment]
Right, using the `/profile` command line switch is currently the only way to launch a custom profile.

Is your default profile broken in any way? Or is there another reason why you consider the configuration _outdated_?

**Comment by pjmlp** [comment]
Yes, it maps to an old GCP account no longer in use for project delivery. 

Ideally I would be able to set the new account as default and delete the no longer valid one.

**Comment by jpassing** [comment]
A profile isn't tied to a specific account, so you can sign out and sign in again with a different account. Would that solve the issue?

**Comment by pjmlp** [comment]
Only partially, as it messed up my credentials for whatever reason, and now I was forced to authenticate via the regular RDP (which generates conflicts with my regular Windows account), versus the in-app login login process for credential generation.

The mapping of profiles and accounts is also not that clear from the existing documentation, I may add.

Anyway I can survive with its current state for the extent of the project, my feedback was trying to have the whole app more user friendly from Windows users point of view.

**Comment by jpassing** [comment]
> Only partially, as it messed up my credentials for whatever reason, and now I was forced to authenticate via the regular RDP (which generates conflicts with my regular Windows account), versus the in-app login login process for credential generation.

What might help is to unload the project and add it again. This causes IAP Desktop to remove all connection settings (incl. saved Windows credentials) for that project.

Or you could go one step further and delete your entire default profile by deleting (or renaming) the registry key `HKEY_CURRENT_USER\SOFTWARE\Google\IapDesktop\1.0`. IAP Desktop will then create a fresh default profile on next launch.

> The mapping of profiles and accounts is also not that clear from the existing documentation, I may add.

Good point, I'll make a note to fix that.
