### ISSUE TITLE
Disabling "Generate New Windows logon Credentials"

### ISSUE THREAD

**Issue by aymanelbacha** [GoogleCloudPlatform/iap-desktop#1225]
We have hosted an MS SQL instance where external users from another company to access it, yet we need to disable "Generate New Windows logon Credentials" so that they don't impact the access for other users.
Is there any options to remove that as an admin, moreover is there a way to make the SQL admin authentication as the default and disable the Windows authentication
![Uploading disable.PNG…]()

**Comment by jpassing** [comment]
> we need to disable "Generate New Windows logon Credentials"

Generating Windows credentials requires the `compute.instances.setMetadata` permission on the VM instance or the enclosing project. This permission is part of the _Compute Instance Admin_ and a few other roles. If the VM has an attached service account, generating credentials additionally requires the `iam.serviceAccounts.actAs` permission on the service account or enclosing project. This permission is part of the _Service Account User_ role.

If want to make sure that users can't generate Windows credentials, make sure that you don't grant them these permissions/roles.

When you connect to a Windows VM using IAP Desktop and haven't configured any credentials yet, you typically see this dialog:

![image](https://github.com/GoogleCloudPlatform/iap-desktop/assets/5724941/98008c24-9136-4660-ad60-56521c9503ef)

Before showing that dialog, IAP Desktop actually checks whether you have the the `compute.instances.setMetadata` permission -- and if you don't, it won't even show the _Generate new credentials_ option. I guess this is the behavior you're looking for?


> is there a way to make the SQL admin authentication as the default and disable the Windows authentication

You can disable SQL Server Windows authentication in the connection settings -- either for individual VMs, zones, or entire projects:

![image](https://github.com/GoogleCloudPlatform/iap-desktop/assets/5724941/578e7233-a34c-4060-ac27-9d6714296a0f)

But this setting only applies to you, there's currently no way to disable the option for all users of a project.

**Comment by aymanelbacha** [comment]
hi @jpassing,
Thanks for sharing the above.
Indeed that's what I was looking for, mistakenly putting the compute Instance Admin ROLE, now after changing it to Compute Viewer it has the limited privileges.

**Comment by jpassing** [comment]
Thanks for confirming, I'll close the issue then.
