### ISSUE TITLE
Need PWA for Chromebooks

### ISSUE THREAD

**Issue by chromestrong** [GoogleCloudPlatform/iap-desktop#127]
Please create a Progressive Web Apps version of this so it can be used on Chromebooks.

Thanks

**Comment by jpassing** [comment]
Thank you for this feedback. I agree that some kind of PWA would be nice, but I am not sure if there are any plans to build something like this. However, I will happily relay that feedback to the relevant people at Google. 

The request is out of scope for this particular project however, so I will close this issue.
