### ISSUE TITLE
Filles download option for IAP Windows VM

### ISSUE THREAD

**Issue by anty123HK** [GoogleCloudPlatform/iap-desktop#1279]
For Linux VM, you can download files from "Session" → "Download" at the top in the IAP UI.
But for Windows VMs, the "Download" item is grayed out.

I know we can copy/paste files in a Windows VM, but this method is restricted because of our security policy. 
Are there any ways to download files from a Windows VM while using IAP?

![image (10)](https://github.com/GoogleCloudPlatform/iap-desktop/assets/159208445/792d6736-6175-42f5-b1b4-8ab8e769652e)

**Comment by jpassing** [comment]
Another option to share files is to redirect your local drives:

1. Open the connection settings for the VM
2. Set **Redirect drives** to **Enabled**
3. Reconnect to the VM

However, if the VM is configured to disallow clipboard sharing, then there's a good chance that it also [doesn't allow drive redirection](https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.TerminalServer::TS_CLIENT_DRIVE_M). These policies are enforced server-side, so there's no way for IAP Desktop to "sidestep" them.
