### ISSUE TITLE
SSH Username Field Does Not Allow Period Character

### ISSUE THREAD

**Issue by dave-pollock** [GoogleCloudPlatform/iap-desktop#1312]
When attempting to save a username containing a period character (`.`) (e.g. `some.user`), the error "Property value is not valid" is displayed with the following details:
```
Specified argument was out of the range of valid values.
Parameter name: Value some.user is not within the permitted range
```

Desired behaviour:
We should be able to use any character from the [Portable Filename Character Set](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_282) because AFAIK that's the official standard for nix user names (from [here](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_437)).

**Comment by jpassing** [comment]
Good catch... yes, IAP Desktop currently [doesn't permit dots in usernames](https://github.com/GoogleCloudPlatform/iap-desktop/blob/2120e7e1b8e3c5ea2289d0fc55f46ed04058bcec/sources/Google.Solutions.IapDesktop.Extensions.Session/Protocol/Ssh/LinuxUser.cs#L34). That was inspired by `shadow-utils`, but it looks like `shadow-utils` [relaxed their rules some time back](https://github.com/shadow-maint/shadow/commit/cfc981df2afc615e3792b918e9ee49e631b0a3a9). So IAP Desktop should do the same.

**Comment by jpassing** [comment]
Here you go: [IapDesktop-2.40.1423.zip](https://github.com/GoogleCloudPlatform/iap-desktop/files/14532310/IapDesktop-2.40.1423.zip) (zipped because GitHub doesn't permit `.msi` attachments).
