### ISSUE TITLE
Cannot access google cloud project 

### ISSUE THREAD

**Issue by jahVaruka** [GoogleCloudPlatform/iap-desktop#1313]
After signin, cannot redirect to IAP application 

![image](https://github.com/GoogleCloudPlatform/iap-desktop/assets/87408104/ec8a1195-7dc1-4a5c-99fe-2ddaa3551528)

![image](https://github.com/GoogleCloudPlatform/iap-desktop/assets/87408104/25c43566-9f47-4a5f-aeb0-44c0d0a11972)

IAP version 2.40.1418

**Comment by jpassing** [comment]
This is most likely an HSTS issue: At some point, you might have run a web server on your local machine that set an HSTS header that instructed Chrome to only accept HTTPS connections from localhost. This setting now prevents Chrome from posting the sign-in result back to IAP Desktop over HTTP.

You can clear the Chrome HSTS state for `localhost` by doing the following:

1. In Chrome, open `chrome://net-internals/#hsts`
1. Under **Delete domain security policies**, enter `localhost` and click **Delete**.

Then try signing in again.

**Comment by jpassing** [comment]
Did clearing the HSTS state in Chrome help? If not, please reopen the issue.
