### ISSUE TITLE
System.OutOfMemoryException

### ISSUE THREAD

**Issue by bt-zdunning** [GoogleCloudPlatform/iap-desktop#1392]
IAP Desktop Version `2.41.1463.0`

I constantly receive `System.OutOfMemoryException` errors when using IAP desktop, even when I have plenty of memory available on my machine.

This happens when trying to RDP/SSH into an instance, or add a new project in Project Explorer. I've seen it where I'll be around 50% memory utilization and will still receive the error.

**Comment by jpassing** [comment]
Assuming you're currently using the 32-bit version of IAP Desktop, could you try if switching to the [64-bit (x64) version](https://github.com/GoogleCloudPlatform/iap-desktop/releases/download/2.41.1463/IapDesktopX64.msi) helps? 

It's quite likely that you're not _really_ running out of memory, but that the 2GB of virtual memory space that a 32-bit process has is becoming too fragmented, causing larger memory allocations to fail. This situation is not uncommon when using multiple RDP sessions in parallel (#1203) as the RDP control tends to consume a fair amount of virtual memory for each session.

**Comment by jpassing** [comment]
Did switching to 64-bit resolve the problem? If not, please reopen the issue.
