### ISSUE TITLE
Feature Request - Allow Files/Folder Drag and Drop for Windows RDP

### ISSUE THREAD

**Issue by Nicolas-Arnaise** [GoogleCloudPlatform/iap-desktop#1401]
Hello,
Could it be feasible to have in a future release a support for Drag&Drop files or folders between host Windows and remote Windows Server through the IAP RDP window ?
As mentionned in issue #633 the copy/paste works to transfer files but when we use it to copy a large folder (taking multiple minutes to complete), if anything else enter the host Windows Clipboard the current transfer breaks.
Also dragging and dropping looks more user friendly than a copy/paste between remote and host.

Thanks 😊

**Comment by jpassing** [comment]
I looked into this, but unfortunately it doesn't seem feasible. IAP Desktop uses the same (Windows-builtin) RDP component as `mstsc.exe`, and this component currently doesn't support drag and drop.

Another option to copy files would be to enable drive redirection (**Connection settings** > **Redirect drives**). Maybe that's an option?

I'll close this issue as I don't think there's anything we can do at the moment. But please let us know if you have further ideas or feedback!
