### ISSUE TITLE
How can we manage projects?

### ISSUE THREAD

**Issue by llomgui** [GoogleCloudPlatform/iap-desktop#1403]
Hello,

I have multiple "inaccessible project" and unwanted projects.
How can we remove them from the listed projects?

Thank you

**Comment by jpassing** [comment]
Right-click the project and select **Unload project**. 

This removes the project from IAP Desktop.

**Comment by llomgui** [comment]
It doesn't work on deleted project.
![image](https://github.com/GoogleCloudPlatform/iap-desktop/assets/14892748/319cbfe9-25f4-4665-a066-9e24c1fc1700)

**Comment by jpassing** [comment]
What probably happened here is the following:
1. You unloaded one of the deleted projects
2. IAP Desktop then tried to refresh the list of projects, but encountered another deleted project
So the error message is not about the project you just unloaded, but about another deleted project.

To unload multiple projects, a better approach might be the following:

1. Right-click the **Google Cloud** node in the Project Explorer window
2. Select **Unload projects...**
3. Select all projects you want to unload, then clidk **Unload**

**Comment by jpassing** [comment]
I assume this is resolved now? If not, please re-open the issue.
