### ISSUE TITLE
Feature Request: Add Reconnect and Logoff commands to connection tab context menu

### ISSUE THREAD

**Issue by bryanfarrell** [GoogleCloudPlatform/iap-desktop#1463]
I have regularly used Devolutions Remote Desktop Manager for years for on prem server management.  Like IAP desktop, it has a feature to associate a VM instance with connection settings at a folder (IAP project) or VM instance level.  Like IAP desktop this allows us to set our credentials for each VM instance or IAP project once, so we don't have to re-enter them every time we want to connect to a VM instance.

What Devolutions RDM has that IAP desktop does not is two key features I use very often when managing on prem servers, which would also be very beneficial in IAP desktop.  These features would exist in the context menu of the VM instance tab in the main window of IAP desktop which shows the remote session.

The two features would be a 'Reconnect' command and a 'Logoff' command.  Our IAP VM instances lock the remote session after a short time, so when I login the first time, IAP desktop uses the configured credentials to log me in without entering my password.  However, when the session locks, my only options now are to re-enter my password each time, or to close my connection by clicking the X in the VM instance tab, and then double clicking the VM instance name in the Project Explorer again, which then uses the saved credentials to log me back in so I can continue working where I left off.

This is cumbersome when debugging an issue that spans a half a dozen VM instances, as I have to filter the Project explorer for each VM name, then reconnect one at a time using the method I described above.

In contrast, in Devolutions RDM, if my session has locked, I can simply right click on the VM instance tab and select 'Reconnect'.  That process simply automates the process of doing what I described above, namely clicking X on the VM instance tab, then double clicking on the VM instance name in Project Explorer to reconnect to the VM instance.

This 'Reconnect' feature would seem to be something rather simple to implement, as it could do exactly as I just described: execute the code when the user clicks X on the VM instance tab, then execute the code when the user double clicks on a VM instance in Project Explorer.

The second option, 'Logoff' would also be helpful to make sure users properly log off of VM instances when they are done, which in my experience does not happen the majority of the time.  I am not sure how Devolutions RDM programmatically issues the logoff command (perhaps it's an RDP protocol command), but if there is something similar in the IAP protocol, it would be great to have that option too.

If nothing else the 'Reconnect' option would be what is most ideal, as that is the issue I am currently having to deal with quite a lot and having it would be a huge quality of life improvement to IAP desktop as well as a big-time saver.

I hope you will consider looking into adding the 'Reconnect' option and also possibly the 'Logoff' option if that is possible as well.

Thank you for your time,
Bryan Farrell

**Comment by jpassing** [comment]
Thanks for this suggestion and the detailed explanation, I agree that these would be good features to add.

**Comment by jpassing** [comment]
[Here's a (signed) installer package of the latest development build, `2.43.1612`](https://issuetracker.google.com/action/issues/373484790/attachments/60072127?download=true). This build includes 2 new commands in the session menu:

![image](https://github.com/user-attachments/assets/69bb157c-0307-4e7c-9780-8390661ca8a2)

* **Reconnect** disconnects the session and immediately connects it again.
* **Sign out** performs the equivalent of a **Start > Sign out** and then disconnects the session.

RDP doesn't seem to provide any mechanism or API to remotely trigger a timeout. So what the **Sign out** does is perform the equivalent of hitting `Ctrl+Alt+Esc, Down, Down, Enter`. That's not guaranteed to work in all cases, but it has been working very well in my own testing so far -- with the exception of Windows Server Core VMs.

If you have the time, it would be great if you could give this version a try and let me know if it works as you expected.

**Comment by jpassing** [comment]
These two features (Reconnect and Sign-out) are now available in [release 2.43](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.43.1627).
