### ISSUE TITLE
Is this related to chrome remote desktop in any way?

### ISSUE THREAD

**Issue by Noemata** [GoogleCloudPlatform/iap-desktop#1572]
Wasn't sure where to ask this question, sorry if this is misdirected.  Is this project related to chrome remote desktop in any way?  I really like the server and client portions of chrome remote desktop, but the client portion has been deprecated.  It doesn't always make sense to do everything through the browser, so I'm wondering if there's any prospect of making this project access chrome remote desktop and if there's any prospect of open sourcing the server component?

**Comment by jpassing** [comment]
IAP Desktop is unrelated to [Chrome Remote Desktop (CRD)](https://remotedesktop.corp.google.com/?pli=1). IAP Desktop uses RDP and SSH and tunnels connections over IAP TCP-forwarding. For the purpose of administering VMs, that has a few benefits over CRD, especially in corporate environments:

- You don't need to install anything on the target VM.
- You have fine-grained control over who can access which VM, and over which protocol -- and it's all integrated with IAM.
- You can control how the traffic flows from clients to VMs and, for ex, route it thru Private Service Connect.
- You can use the same authentication mechanism that you'd normally use (for ex, OS Login for Linux or Active Directory for Windows).
- You can also use it for [other protocols](https://googlecloudplatform.github.io/iap-desktop/connect-other-applications/).

> but the client portion has been deprecated

What _is_ deprecated is [Chrome RDP for Google Cloud Platform](https://chromewebstore.google.com/detail/chrome-rdp-for-google-clo/mpbbnannobiobpnfblimoapbephgifkm?pli=1#:~:text=The%20only%20true%20Microsoft%20Remote,running%20on%20Google%20Compute%20Engine.) Despite its name, this extension had nothing to with Chrome Remote Desktop and was simply an RDP client, implemented as a Chrome extension.

Chrome Remote Desktop is part of the Chrome project and not deprecated. 

Does this answer your question?

**Comment by Noemata** [comment]
Question answered.  Thank you for the clarifications. So where would I direct my queries regarding the server side of Chrome Remote Desktop?  I find it quite useful for creating across the world connections to my tiny business setup (6 servers + 5 workstations).  I'm often on the road and need to administer things securely and easily.  The one significant drawback, and I'm not sure if this is server side or client side, is that I can't use my remote microphone in situations where I want to use my home business workstations for Zoom/Teams/etc. calls.  There are also instances where it is more secure to operate from those systems when abroad.  I was hoping to speak to someone about this.  I'm even able to contribute audio interface code toward this if there was some way to contribute toward the code base.

Thanks again for responding.  Would appreciate some contact information regarding the server side of Chrome Remote Desktop.

**Comment by jpassing** [comment]
For instructions on using CRD with Compute Engine, see [Set up Chrome Remote Desktop for Linux on Compute Engine](https://cloud.google.com/architecture/chrome-desktop-remote-on-compute-engine) or [Set up Chrome Remote Desktop for Windows on Compute Engine](https://cloud.google.com/architecture/chrome-desktop-remote-windows-compute-engine#non-interactive_installation).

I believe that the source code for the server-side components is part of the [Chromium sources](https://source.chromium.org/chromium/chromium/src/+/main:remoting/), but I'm not familiar with the details.

**Comment by Noemata** [comment]
Thank you again.  You got me very close to the "problem".  The current code does not support a remote microphone.  Audio capture is all there, just not a facility to connect with a remote audio input source.  Interesting.  Clearly, this is the repo for submitting issues related to this limitation.  What is missing from this code are the bits that integrate with Google's RDP routing servers where security is handled.  Not necessarily a problem, but it might not be possible to build a working server side installer without those elements.  It's not obvious from a cursory examination of the code whether all the installer bits are there.

Thank you for hunting this down.  Very, very helpful.  I'd rather be working with the code in your repo here (tidy, nicely structured, complete)! ;-)
