### ISSUE TITLE
Unable to authenticate IAP

### ISSUE THREAD

**Issue by abhigupta3443** [GoogleCloudPlatform/iap-desktop#226]
I am trying to use IAP Desktop to log into my GCP instances. However, when I am trying to log into the IAP desktop application using my Google account, it is not allowing me to authenticate at all. Ideally when you click on "Sign in with Google" it should pop open a browser window to authenticate. But in my case, it gives error as "Authorization Failed: network location cannot be reached". Just to be clear, the browser is not at all opening to complete the sign in steps. 

![J92SQ](https://user-images.githubusercontent.com/69185123/89257316-8c1bb380-d643-11ea-882c-89d5ceb4c199.png)

**Comment by jpassing** [comment]
After you've completed the sign-in steps in the browser window, IAP Desktop opens connections to `https://oauth2.googleapis.com/`, `https://accounts.google.com/` and `https://openidconnect.googleapis.com` to complete the authorization. One of these requests seems to fail. 

Are you able to open these 3 URLs in Internet Explorer? Note that it's important to use IE and not any other browser for this test as IE and IAP Desktop use the same source for network settings. If IE does not work either, then I suspect your network or proxy settings are the culprit.

**Comment by jpassing** [comment]
I am closing this as I have not heard back from you. Please feel free to re-open the issue if the problem persists.
