### ISSUE TITLE
Creating windows credentials times out

### ISSUE THREAD

**Issue by informajojo** [GoogleCloudPlatform/iap-desktop#27]
Hi again,
I have tried to change RDP  password from RDCMan, and it throws an error after a while with a "timeout".
However, it looks like in the serial logs that the operation was successful:
11/13/2019 9:27:51 AM UTC: Creating a new user account for xxx.
11/13/2019 9:27:51 AM UTC: Adding user...
11/13/2019 9:27:51 AM UTC: User accounts updated.

11/13/2019 9:29:23 AM UTC: Creating a new user account for xxx.
11/13/2019 9:29:23 AM UTC: Username already exists. Changing password...
11/13/2019 9:29:23 AM UTC: User accounts updated.

Nothing urgent, just to let you know.
-Johan

**Comment by jpassing** [comment]
Hi Johan,

a few questions:

* are you seeing the error message _Timeout waiting for password reset_ or a different error message? 
* does the error occur every time or only intermittently?
* does viewing the serial port (_Show serial port output_ in context menu) work for you?

Johannes

**Comment by informajojo** [comment]
Hi Johannes,
Yes I see that timout message.
So far it has happened every time, but only the first time it was logged in the serial log, the other attempts appear to have been unsuccessful. Connecting to the server works fine but also the serial log although it displays it does seem to be old, possibly a cached version (?), not sure how that works.
Johan

**Comment by jpassing** [comment]
I am having trouble reproducing this issue or figuring out what might be causing this. A few more questions:
* Is this only happening with a single VM or multiple VMs?
* Which IAM role(s) does the user have on the GCP project
* When you open `cmd` on a VM and run `echo test>COM1`, does that show up in the serial port output window?

**Comment by informajojo** [comment]
Hi have tried again with a server where I hadn't tried before:
In the console it looks like this:
11/29/2019 1:29:46 PM UTC: Creating a new user account for xxx.
11/29/2019 1:29:46 PM UTC: Username already exists. Changing password...
11/29/2019 1:29:46 PM UTC: User accounts updated.

Is it possible it has anything to do with me changing username (it proposes my windows account name)?
Another possibility is that this is agian based on a pretty old image. But I have tried also with a brand new n2 image, and I got the same issue. This was in version 1.1.22. Not sure if I could build the plugin and hook up the debugger? I downloaded the source code but I haven't seen how to build/publish.

**Comment by informajojo** [comment]
and yes, the echo test thing works fine

**Comment by informajojo** [comment]
and the user is an editor of the project (or actually, the owner)

**Comment by jpassing** [comment]
Would you mind testing if https://github.com/GoogleCloudPlatform/iap-windows-rdc-plugin/releases/tag/1.1.32 fixes the issue? Thanks.

**Comment by informajojo** [comment]
sorry after installing this the plugin is no longer loaded in RDCMan...

**Comment by informajojo** [comment]
ok yeah I have installed 1.1.32 but there is the same issue. The password is changed, but the response never gets to the client so it times out.
The serial log looks good:
12/12/2019 10:51:45 AM UTC: Creating a new user account for xxx.
12/12/2019 10:51:45 AM UTC: Adding user...
12/12/2019 10:51:45 AM UTC: User accounts updated.

**Comment by jpassing** [comment]
Thank you for verifying. I am sorry that fix was not sufficient to fix the error.

I have a few more questions:

* When you look at serial port 4 of the respective VM in the Cloud Console, can you see that a line like `{"encryptedPassword":"EmXznt+5flyLqxgt9LSdGr ... ` is printed after generating a new password? Somehow the plugin fails to read that output.
* Do you have the Cloud SDK installed on the same machine? If so, does `gcloud compute reset-windows-password [instance]` work reliably?
* Do you use a proxy or anything that could have an impact?

**Comment by informajojo** [comment]
In Cloud SDK on the same machine it looks like this
Resetting and retrieving password for [x] on [y]
No zone specified. Using zone [asia-south1-a] for instance: [y].
Updated [https://www.googleapis.com/compute/v1/projects/xxxx/zones/asia-south1-a/instances/y].
ip_address: x.x.x.x
password:   
username:   x

In the serial log 4 there is the "encrypted password" e.g.

{"encryptedPassword":"EDsdfsdfsdfQ==","passwordFound":true,"userName":"x"}

**Comment by informajojo** [comment]
One more thing that might or might not help (I have never used serial logs). If I list the log from the console, I get all the password resets for that server in the log. At the bottom it says

Specify --start=3510 in the next get-serial-port-output invocation to get only the new output starting from here.

Not sure if this is normal.

**Comment by jpassing** [comment]
After some more testing, I realized that the JSON response is sometimes read in two pieces, which causes the operation to time out. It only happened to me in maybe 1% of the cases, so I am not sure if it is really the same issue as you are seeing. I fixed that issue in https://github.com/GoogleCloudPlatform/iap-windows-rdc-plugin/releases/tag/1.1.44.

If the issue persists, you can now also enable tracing:

* In the Settings dialog, set _Tracing_ to _Verbose_ 
* Restart RDCMan
* Run [DbvView](https://live.sysinternals.com/Dbgview.exe) to observe trace output

Note that tracing adds a good amount of overhead to tunneling, so you should only turn that on temporarily.

**Comment by informajojo** [comment]
Ok thanks for trying, I have restarted using the updated version, without success. It looks like it assumes the response is waiting for more bytes to come, but nothing comes.
I have attached the log file.
[rdcman updatepassword.LOG](https://github.com/GoogleCloudPlatform/iap-windows-rdc-plugin/files/4029680/rdcman.updatepassword.LOG)

**Comment by jpassing** [comment]
Does this problem still apply to the latest version of IAP Desktop? 

I've made several fixes and optimization to the password-reset logic over the course of the past releases, so I wonder whether that might have addressed this issue?

**Comment by informajojo** [comment]
Hi,
Last time I tried it was working fine with completely new images but didn’t work (sometimes, not sure why) when I tried on an old (2-3 years old) image. So for me the problem is less and less of an issue.
Thanks for your support,
Best regards
Johan

**Comment by jpassing** [comment]
Thanks for following up. As it turns out, the fact that you used an old image was an important hint and I was able to reproduce the issue with the (rather ancient) `projects/windows-cloud/global/images/windows-server-2012-r2-dc-v20160112` image.
