### ISSUE TITLE
Authentication error when trying to connect to a VM. Error code 519

### ISSUE THREAD

**Issue by danpriori** [GoogleCloudPlatform/iap-desktop#279]
Whenever I try to connect to a VM by IAP I'm getting the authentication error and saying that the credentials supplied to the package were not recognized (see the screenshots below). 

I tried to create a TCP forwarding but with no success either. I disabled all firewalls in my local as well. 
Other co-workers inside the same network+proxy and permissions are able to connect normally using their computers. It happens probably only inside my computer (we tried with different users on my computer and no success as well)

However, if I try to connect by Windows Remote Desktop Connection application with this tunnel then I manage to connect to the VM.
But with IAP Desktop I'm still getting the error. 

![iap_error1](https://user-images.githubusercontent.com/4473965/95585354-6776fa00-0a3f-11eb-8e37-84cc11e01bf0.PNG)
![iap_error2](https://user-images.githubusercontent.com/4473965/95585369-6a71ea80-0a3f-11eb-8cdf-98c043336594.PNG)
![iap_error_config](https://user-images.githubusercontent.com/4473965/95585376-6c3bae00-0a3f-11eb-8cb1-080919dec4e4.PNG)

Any insights on that?

Thank you!

**Comment by jpassing** [comment]
The error comes straight from the RDP ActiveX and is pretty generic, so I am not sure yet what could be causing this... a few questions:

* Does this issue only occur when you try to connect to a specific VM or does it occur with multiple different VMs?
* Which OS version are you running locally and on the server?

> However, if I try to connect by Windows Remote Desktop Connection application with this tunnel then I manage to connect to the VM.

I assume you created a tunnel by using `gcloud compute start-iap-tunnel ...` and then used the Windows Remote Desktop Connection app to connect to `localhost:<port>`? And this was on the same computer where IAP Desktop showed an error, right?

Could you try to reproduce the IAP Desktop error once more and then check whether there are any warning/error records written to 
**Application and Services Logs >Microsoft >Windows >
TerminalServices-ClientActiveXCore** in Windows Event Viewer (on your local computer)?

**Comment by danpriori** [comment]
Hi!

_- Does this issue only occur when you try to connect to a specific VM or does it occur with multiple different VMs?_
Yes, it occurs with any VM I try to connect in our GCP. Not just one single VM :( 

_- Which OS version are you running locally and on the server?_
Local: Windows 10 Pro 10.0.19041. Server: Windows Server 2019.

- _I assume you created a tunnel by using gcloud compute start-iap-tunnel ... and then used the Windows Remote Desktop Connection app to connect to localhost:<port>? And this was on the same computer where IAP Desktop showed an error, right?_
Exactly. I tried by a tunnel with the command `gcloud compute start-iap-tunnel ...` and it is working fine using the Windows RDC.

Btw, my IAP version is 2.7.315 but it happens with some older version as well.

And please see below the error logs from **TerminalServices-ClientActiveXCore** when trying to connect:

But two warnings happen:
**RDPClient_SSL: An error was encountered when transitioning from TsSslStateHandshakeInProgress to TsSslStateDisconnecting in response to TsSslEventHandshakeContinueFailed (error code 0x80004005).**
and 
**RDPClient_TCP: An error was encountered when transitioning from TcpStateExpectingX244CC to TcpStateFailure in response to TcpEventErrorProcessingX224CC (error code 0x80004005).**
[event_log.zip](https://github.com/GoogleCloudPlatform/iap-desktop/files/5372277/event_log.zip)

Thank you!

**Comment by jpassing** [comment]
Thanks for checking and sharing the event log details. Unfortunately, I do not have a good idea yet on what might be causing this error.  A few more questions:
* As the error seems to be related to TLS -- do the VMs use the self-signed RDP certificate that GCP generates by default? Or do you use any custom/CA/ADCS-issued certificates?
* Are the VMs domain-joined? If so, are you aware of any RDP-related group policies that are applied to the VM?
* Have you tried re-generating credentials to see if that makes any difference?

**Comment by danpriori** [comment]
Hi!

_As the error seems to be related to TLS -- do the VMs use the self-signed RDP certificate that GCP generates by default? Or do you use any custom/CA/ADCS-issued certificates?_
R: Yes. We use the self-signed RDP certificate that GCP generates by default.

_Are the VMs domain-joined? If so, are you aware of any RDP-related group policies that are applied to the VM?_
The VMs aren't domain-joined, so there should be no group policies AFAIK.

_Have you tried re-generating credentials to see if that makes any difference?_
Yes. Many times with also different users/pass :D 

The thing happens on my laptop only. Other accounts also fail on this laptop but not on others. However, as I said, I manage to enter by Windows RDC app even on this laptop. I disabled all local firewalls as well with no success.

**Comment by danpriori** [comment]
Hi again!

We can close this issue. 

Something happened with the account registration on my laptop because after I renewed the password of my business account, then IAP was unable to link with this account again and then it popped up a Windows panel requesting that I try to connect in another way to the VM via IAP (similar to what happened before with Windows RDC app), and this time I forced the connection via my business account again with the new password and this time it worked \o/.

Thank you anyway!

**Comment by jpassing** [comment]
Not sure why the password change suddenly fixed it, but I am happy to hear that it works now.

Please re-open this issue in case the problem reappears.

**Comment by taatuut** [comment]
I had a similar experience and was able to solve it by adding just a qualifier before the user name. Maybe relevant to know for future reference.

A RDP login with only user name emil_zegers suddenly failed with the message you mention.

Using something like anydomain\emil_zegers or niceweather\emil_zegers works. Apparently a qualifier is required (since...)? Using a machine qualifier like .\emil_zegers should be sufficient for local user accounts.

My Windows VMs are not in any way connected to a specific domain or using AD for user management.

**Comment by jpassing** [comment]
> Apparently a qualifier is required (since...)? Using a machine qualifier like .\emil_zegers should be sufficient for local user accounts.

Yes, you need to specify a qualifier if you connect from a domain-joined computer (your local workstation) to a non-domain joined VM. 

As of version 2.10, IAP Desktop automatically sets **Domain** to `.` when generating credentials. This should help avoid the issue. But it can still happen if you manually enter username/password.

**Comment by k-byun** [comment]
reopened on #854
