### ISSUE TITLE
Are there plans for Linux?

### ISSUE THREAD

**Issue by raijinsetsu** [GoogleCloudPlatform/iap-desktop#282]
For those of us running on Linux, this application seems like it would be a huge boon. We would not have to drop to a shell to setup an IAP proxy and then hop over to our RDP client of choice, plug in localhost and the port. It would be one step.

So, the question is: are there any plans to have a variant of iap-desktop for Linux? Theoretically, you could wrap a number of well-used RDP clients.

**Comment by taoszhanna** [comment]
+1 on this especially if it could be a Chromium-based solution, that would also solve for Chromebooks.

**Comment by jpassing** [comment]
Many of the libraries and components underpinning IAP Desktop are specific to Windows. As the goal of IAP Desktop is to provide a "Windows-native" user experience to access VM instance, this dependency on Windows isn't accidental.

Unfortunately, it also means that porting IAP Desktop to Linux or Mac would require a substantial effort, possibly even a rewrite from scratch. A portable version might also involve significant sacrifices w.r.t. providing a "native" user experience.

For now, the priority for IAP Desktop remains on Windows (as client OS) exclusively. I'm therefore closing this FR.
