### ISSUE TITLE
Support for Outbound Proxy Authentication

### ISSUE THREAD

**Issue by smartyr73** [GoogleCloudPlatform/iap-desktop#302]
Are there plans to support proxy authentication?  In a scenario where outbound internet access is via a corporate outbound proxy, some proxies require authentication.  When using IAP desktop, after the confirm your choices option from your Google account (For the permissions for IAP Desktop), IAP desktop then comes back with a 407 error  stating:

An error occurred while sending this request:

WebException:
The remote server returned an error: (407) Proxy Authentication Required

Tests from other proxies not requiring authentication work without issue.

**Comment by jpassing** [comment]
[Version 2.8](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.8.352) added support for proxy authentication, could you give this a try?

**Comment by smartyr73** [comment]
Hi,

So I've tested this and I am still having issues it seems.  The error message I am getting is saying:

"IAP Desktop failed to complete the OAuth authorization.  This might be due to network communication issues

An error occurred while sending the request.

An error occurred while sending the request.  The underlying connection was closed.  An unexpected error occurred on a send.   The handshake failed due to an unexpected packet format".

I am trying to do some network diagnostics at my end to determine the cause of the issue.  I suspect it may be an issue with the configuration of some of the corporate proxies, as I don't see this issue with all of the proxies, just some of them, so I am trying to determine what the common factor is.

Now I only see this issue when I've been through all the authorization steps on my corporate Google account and click on the final Allow step.

I've tested from the browser and I seem to be able to connect to the following URLs fine.

https://oauth2.googleapis.com 
https://accounts.google.com 
https://openidconnect.googleapis.com

I'll keep you updated and let you know when I get something back.

**Comment by jpassing** [comment]
_The handshake failed due to an unexpected packet format_ could be a HTTP vs. HTTPS mix up -- is it possible that the proxy that you've configured in IAP Desktop only supports HTTP and you need to use a different proxy server/port for HTTPS?

Note that all connections made by IAP Desktop are HTTPS.

**Comment by smartyr73** [comment]
Hi,

OK, after some diagnostic and Wireshark traces later, I think I've been able to track down the issue.

When configuring the proxy settings to use this proxy.pac file, it gives the above error, however, when we bypass the .pac file and connect to the proxies directly, it seems to work fine.  So I have a workaround for now, but it would be great if it could support use of .pac files in the future.

**Comment by jpassing** [comment]
Thanks for taking the time to analyze this and sharing the result.

I suppose the solution here would be to extend the options (in Tools > Options > Network) so that you can configure a PAC URL in combination with username/password. That seems reasonable and I added it to the backlog.

**Comment by jpassing** [comment]
Implemented in https://github.com/GoogleCloudPlatform/iap-desktop/pull/326, this feature will be part of the next release

**Comment by smartyr73** [comment]
That's great thanks.  When it's released, I'll test it against several different .pac files that I commonly use and feedback to you.

**Comment by jpassing** [comment]
I published [release 2.10](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.10.414), it would be great if you could give it a try in your environment.

Two caveats I noticed in my testing:

* If you have an error in your PAC file, the PAC is silently ignored. 
* If the computer is subject to a group policy and the group policy specifies a PAC URL, then the PAC URL you configure in IAP Desktop is also silently ignored.

This behavior is not great, but there seems to be little I can do about it since the PAC handling is done by WinHTTP and WinHTTP does not report any errors back to the application.

**Comment by smartyr73** [comment]
I've just tested this using the proxy.pac option, with several different .pac files, and with and without authentication and everything looks good to me. Thanks for the quick turnaround on this.

**Comment by jpassing** [comment]
Great, thanks for letting me know. I'll close this issue then.
