### ISSUE TITLE
IAP-Desktop 402 Error

### ISSUE THREAD

**Issue by mxln** [GoogleCloudPlatform/iap-desktop#305]
We would like to use the IAP-Desktop to connect from a corporate network to Windows machines running on the GCP. 
Currently we are still facing issues setting up a proper connection. Even after adding proxy configuration the following error message occurs:
"(402) Zahlung erforderlich" / (Payment required)

Do you know, what exactly causes this error message and how to fix it?

Extract from the serial port logging:
...
xxx GCEGuestAgent: GCE Agent Started (version 20200813.01)
xxx OSConfigAgent Info: OSConfig Agent (version 20200901.01) started.
xxx GCEMetadataScripts: Starting startup scripts (version 20200129.00).
xxx GCEMetadataScripts: No startup scripts to run.
... (the connection seems to be working somehow)

**Comment by jpassing** [comment]
When are you seeing the error message, right after signing in? Or when you try to connect to a VM instance? Does the error dialog contain any additional details?

The fact that the error message is in German seems to indicate that it's coming from the proxy server, not from the Google API itself. The Google API error messages are always in English and I don't think there's ever a case where it would return a 402.

It it possible that your proxy server is using the 402 code to indicate that the URL is not allowed, or that something else is needed?

**Comment by mxln** [comment]
Thank you for you fast response. I did not think of that at first. You are right, it must be related to the proxy. I will let you know, if we could solve the problem. Thanks again.
