### ISSUE TITLE
Can't Fullscreen, then crash

### ISSUE THREAD

**Issue by wizardor** [GoogleCloudPlatform/iap-desktop#311]
Expected behavior:
* Step 1: When I run RDP (windows server 2019) and start with the F11 function, then it crash
* Step 2
* ...

Observed behavior:
* Step 1: can enable Fullscreen function
* Step 2
* ...

Installed version: 2.8.352.0
.NET Version: 4.8.4250.0
OS Version: Microsoft Windows NT 10.0.19041.0

**Comment by jpassing** [comment]
Thanks for reporting this bug. 

I was able to reproduce this when using the F11 shortcut. Entering full screen via the menu **Desktop > Full screen** seems to work fine.

**Comment by jpassing** [comment]
The fix will go into version 2.9, which will be released in approx. 2 weeks.
