### ISSUE TITLE
Multiple monitor support

### ISSUE THREAD

**Issue by itspage** [GoogleCloudPlatform/iap-desktop#352]
I know this is possible with the RDP client, but does the library iap-desktop uses support it?

**Comment by jpassing** [comment]
I did some research on this -- adding multi-monitor support is a bit tricky, but it's possible. I think it would be a good feature to add.

**Comment by jpassing** [comment]
I got multi-screen support to work in a dev branch. There is a catch though: If you have multiple screens, I basically take the union of the screens' sizes and positions to determine the full screen area. For two same-size screens, this works well:

![image](https://user-images.githubusercontent.com/5724941/103478420-d6f25080-4dc6-11eb-8148-a60de0b58951.png)

If you have 3 screens positioned like this, you get dead areas though:

![image](https://user-images.githubusercontent.com/5724941/103478680-a0b5d080-4dc8-11eb-8f0c-d9b660a9efe9.png)

And then there is the issue that different screens could have different scaling settings. If the bottom screen has 125% scaling while the top screens have 100%, the result is that the bottom screen is not full occupied:

![image](https://user-images.githubusercontent.com/5724941/103478497-744d8480-4dc7-11eb-9fd5-43b6eebaa42c.png)

Theoretically, these issues could be avoided by using the [UseMultimon](https://docs.microsoft.com/en-us/windows/win32/termserv/imsrdpclientnonscriptable5-usemultimon) feature like mstsc. But the trouble is that this cannot be toggled during a session -- so it breaks the ability to switch back and forth between full-screen and normal screen.

One option might be to make the set of screens to use configurable -- in the example above, that would allow you to exclude the bottom screen.

If you have other ideas, please let me know.

**Comment by itspage** [comment]
Appreciate you spending some time on this. I think the equivalent to the "Use all my monitors for the remote session" option in RDP would be a great starting place here. 

If I understand your comment correctly - this would mean we'll always need to launch in full screen if the option is selected and not run windowed. Which is perhaps fine with appropriate messaging?

**Comment by jpassing** [comment]
Implemented in [release 2.11](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.11.481). If you experience any issues with that new feature, please feel free to file a new issue.
