### ISSUE TITLE
Add feature to connect to the VM without requiring compute.instances.list

### ISSUE THREAD

**Issue by racoworks** [GoogleCloudPlatform/iap-desktop#365]
If you connect to a VM either using IAP-Desktop or browser base integration, it looks like compute.instances.list role is required.
If the syntax for connection is iap-rdp:///my-project-123/us-central1-a/my-instance-1, I am already mentioning the instance name as long as IAP-secured Tunnel User is allowed for the user on the VM, it should connect.

On the IAP-Desktop a feature that allows the user to input my-project-123/us-central1-a/my-instance-1 and establish a RDP session without having to have compute.instances.list assigned to the user should help further restricting who sees what.

**Comment by jpassing** [comment]
Thanks for reporting this bug. To connect to a VM instance by URL, all that's needed should be the _IAP-secured Tunnel User_ role (or `iap.tunnelInstances.accessViaIAP` permission)

**Comment by jpassing** [comment]
The fix went into [release 2.11](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.11.481) which was published today.
