### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by fkollmann** [GoogleCloudPlatform/iap-desktop#384]
Hi, 

I would like to contribute some things (because we are currently moving all of our DC systems to the Google Cloud), but I can't get this to build.

It took me a while to figure out that the dependencies have to built separately, but now I am stuck with a missing file `Google.Solutions.IapDesktop\OAuthClient.cs`.

It would be great if you could add a `BUILD.md` and explain how to build the source from a clean checkout :) 

Best Regards, Felix

**Comment by jpassing** [comment]
You're right -- this step is missing in the instructions:

1. [Create a custom OAuth client ID](https://developers.google.com/identity/protocols/oauth2) in the Cloud Console.
2. Copy `sources/Google.Solutions.IapDesktop/OAuthClient.cs.default` and paste the client credentials.

After that, you should be able to build the solution.

**Comment by fkollmann** [comment]
Thanks! Let me provide a step-by-step guide for future readers:

1. Create a new project for testing purpose
2. Create a new external consent screen: https://console.developers.google.com/apis/credentials/consent
3. Leave the scope list empty
4. Add a yourself as test user (enter the email address manually)
5. Finish the wizard
5. Create new OAuth client ID credentials for a Desktop App: https://console.developers.google.com/apis/credentials
6. Copy `sources/Google.Solutions.IapDesktop/OAuthClient.cs.default` and paste the client credentials.

**Comment by jpassing** [comment]
Thanks, I updated the instructions. 

An internal consent screen should typically suffice for development, but of course an external one works too.
