### ISSUE TITLE
Windows resize in IAP on maximize

### ISSUE THREAD

**Issue by umashank68** [GoogleCloudPlatform/iap-desktop#443]
Love this utility - thank you!

When in IAP window if you restore down, then maximize IAP again, open windows on the VM are resized. Is there any way to prevent this from happening while in IAP (vs. maximizing to RDP)?

**Comment by jpassing** [comment]
Thanks, I am glad you like the tool!

By default, the remote desktop is resized to fit the IAP Desktop window. You can change this behavior by going to the connection settings and changing **Desktop Size** from **AutoAdjust** to **ClientSize**. Then the remote desktop size will stay fixed, even if you resize/maximize/restore the IAP Desktop window. On the flip side, you might end up with scrollbars when you change the window size... so I am not sure if that's what you're looking for?

**Comment by jpassing** [comment]
I am closing this issue as I have not heard back whether changing **Desktop Size** fixed the problem or not.

**Comment by coreyman** [comment]
This is an issue for us now. We have users on tiny screens and are needing to use ClientSize instead of AutoAdjust so that they get the scrollbars but the Desktop Size option seems to be missing in the latest version of IAP. Was this intentional? Can we get the option back?
