### ISSUE TITLE
Project Explorer: Filter VM instances by name

### ISSUE THREAD

**Issue by jpassing** [GoogleCloudPlatform/iap-desktop#444]
Add a filter/search box to project explorer so that you can filter VM instances by name,

**Comment by dinesh1844** [comment]
Any update on this. Hopefully looking for a release with Filter/Search box.

**Comment by jpassing** [comment]
You can expect this feature in version 2.16 or 2.17 (~May).

**Comment by jpassing** [comment]
I just released [version 2.6](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.16.594), which now lets you search for instances by name.

Thanks for suggesting this feature!

**Comment by dinesh1844** [comment]
This feature is very helpful. Thanks for implementing it.
