### ISSUE TITLE
Add support for OS Login MFA

### ISSUE THREAD

**Issue by pricey123** [GoogleCloudPlatform/iap-desktop#462]
Adding support for OS Login MFA would allow companies to use this tool as a standard way of accessing servers without the need to use gcloud or another method.
Currently when you try to access a server with MFA enabled, you get a "not supported message".

**Comment by jpassing** [comment]
I agree that this would be a useful feature. I'll look into this.

**Comment by jpassing** [comment]
Thanks for suggesting this feature, it's now available in release [2.17.616](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.17.616).
