### ISSUE TITLE
Support for xRDP

### ISSUE THREAD

**Issue by smartyr73** [GoogleCloudPlatform/iap-desktop#478]
I was wondering if the use case for xRDP has been considered?  

This would allow GUI access to Linux as well as Windows servers, assuming everything is set up correctly on the server side.

I am planning to test this scenario with various Linux distros with IAP desktop.  I'll share the results when I am done.

**Comment by jpassing** [comment]
That's an interesting idea. From a technical perspective, I don't think it should be too difficult to make it work. But I am a bit worried about whether the UX will be very good: xRDP requires a password to log in, but Linux users typically don't have a password on GCP. Either users would have to manually set a password over SSH first (which is awkward) or IAP Desktop would need to provide a "Set password" command to let users set a password. I suppose that's doable (by performing an ssh exec in the background), but it'll make the entire feature more complex...

**Comment by smartyr73** [comment]
Yes, that's a very good point.  It something I've been wrestling with myself and I can't see an easy way around it (If such a thing exists).  I have xRDP working using the SDK, but it always comes back to having to manually login with a password, and the overhead of having to set this up etc. The perfect scenario would be for it to work like the OS login does for SSH access on GCP,  but I don't think this is do-able.  I am still investigating this and what the options would be.

**Comment by jpassing** [comment]
I just realized one more complication -- if the VM uses OS Login, you can't even set a password for your Linux user. Instead, you have to create a separate (non OS Login-managed) user and use that for XRDP. That's obviously making this more complicated and to some extent, also undermines OS Login since that separate user isn't tied to your Google identity in any way.

**Comment by smartyr73** [comment]
Yes, this is an excellent point.  On balance maybe this feature should be left out.

**Comment by jpassing** [comment]
I liked the idea of adding xRDP support, but it's challenging: The UX won't be great (see previous comments), it requires extra setup on the VMs, and performance tends to be worse than "regular" RDP too. Overall, I think it's not worthwhile -- so I'm closing this.

**Comment by smartyr73** [comment]
Yes, all valid points. I'd agree with this 100%.   Thanks for considering it.
