### ISSUE TITLE
tmux displays only blank screen

### ISSUE THREAD

**Issue by nzbart** [GoogleCloudPlatform/iap-desktop#482]
When I log into a Debian 10 VM using SSH and run tmux, I see only a black screen with a cursor in the top left. Typing doesn't appear to have any effect, except for ctrl-d, which exits tmux and drops back to the command line.

Note that tmux on the same VM works well when using the browser based SSH tool in the cloud console.

**Comment by nzbart** [comment]
@jpassing thanks for looking into this. Is the improvement required in VtNetCore or in IAP Desktop?

**Comment by jpassing** [comment]
Both, I think -- I'll probably need to extend vtnetcore to handle this CSI sequence, and extend IAP Desktop to recognize the mode when handling keyboard input.

**Comment by jpassing** [comment]
I just released [release 2.18](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.18.631), which contains a fix.  `tmux` now launches properly and worked fine in my tests:

![image](https://user-images.githubusercontent.com/5724941/120432266-f8596780-c379-11eb-8dd9-95e74d98dfcd.png)

If you notice any further issues or key combinations that don't work, please let us know.
