### ISSUE TITLE
Vim unusable due to escape key not working

### ISSUE THREAD

**Issue by bartecargo** [GoogleCloudPlatform/iap-desktop#483]
I can successfully use Vim in the browser based SSH connection from the Cloud Console, but it doesn't appear possible to use Vim in the IAP desktop SSH connection because the escape key is not correctly sent.

**Comment by jpassing** [comment]
That's odd, `vim` has been working just fine in all previous tests. Is it possible that you have any custom settings in your `~/.vimrc` or `/etc/vim/vimrc` that might play a role here?

Could you also share the vim version and OS image that you're using? That might help reproducing the issue.

**Comment by jpassing** [comment]
Thanks for confirming. The fix will go into the next release.

**Comment by jpassing** [comment]
Thanks again for reporting this bug. The fix is now available in release [2.17.616](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.17.616).

Please re-open the issue if the problem persists after updating to the latest version.
