### ISSUE TITLE
VM window doesn't keep focus when clicked.

### ISSUE THREAD

**Issue by natedogith1** [GoogleCloudPlatform/iap-desktop#490]
VM windows don't get proper focus when being clicked.

How to reproduce:

1. Connect to a VM
2. Select something in the project explorer
3. Click in the VM window to ensure it is focussed
4. Alt-tab to another window
5. Alt-tab back to IAP Desktop
6. Notice that the keyboard focus is now in the Project Explorer instead of the VM window (can tell because something like Alt+F opens the file menu rather than interacts with the VM)

What should happen:
The VM window should keep keyboard focus.

Workarounds:
If Project Explorer isn't selected after a connection is opened, the VM window will maintain focus.

**Comment by jpassing** [comment]
Thanks for reporting this bug. I implemented a fix in release [2.17.616](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.17.616).

Please re-open the issue if the problem persists after updating to the latest version.
