### ISSUE TITLE
Multiple sessions to same host

### ISSUE THREAD

**Issue by pricey123** [GoogleCloudPlatform/iap-desktop#496]
Would it be possible to add a feature to allow multiple sessions to the same host?
We have a host which acts as a bastion host and would require to connect to this multiple times if working on multiple backend servers at the same time.

**Comment by jpassing** [comment]
I assume you're referring to SSH sessions? Yes, that would be possible -- in fact, I was already planning to add that feature.

**Comment by pricey123** [comment]
> I assume you're referring to SSH sessions? Yes, that would be possible -- in fact, I was already planning to add that feature.

Yes, apologies, should have stated which type of session. Sounds great!

**Comment by jpassing** [comment]
I just released [release 2.18](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.18.631), which adds a **connect in new terminal** command to the context menu:

![image](https://user-images.githubusercontent.com/5724941/120432580-6d2ca180-c37a-11eb-945a-d7d530f6478c.png)


Thanks for suggesting this feature!
