### ISSUE TITLE
Numpad Keys are not wokring

### ISSUE THREAD

**Issue by dinesh1844** [GoogleCloudPlatform/iap-desktop#512]
Numpad numeric keys are not working. Initially i thought it would be a keyboard issue but tried with multiple keyboard and multiple system. Same issue in all combinations. Keyboards are working fine in all applications

![1200px-Numpad svg](https://user-images.githubusercontent.com/81134595/122245130-14651900-cee3-11eb-9daa-a40c583ca929.png)

**Comment by dinesh1844** [comment]
This issue is in latest version of IAP

**Comment by jpassing** [comment]
Thanks for reporting this issue, it's probably related to the keyboard translation-related changes introduced in the last version.

Just to confirm: Are you trying to use the number keys (Num Lock ON) or arrow keys (Num Lock OFF), or are they both not working for you?

**Comment by dinesh1844** [comment]
I am facing issue when trying to use Number keys(Num Lock On). But arrow keys are working as expected when Num Lock OFF.

**Comment by dinesh1844** [comment]
And it would be helpful if you fix the default location of scroll as by default it is location down the Scroll bar.


![WhatsApp Image 2021-06-17 at 1 04 28 PM](https://user-images.githubusercontent.com/81134595/122352378-b5e47d00-cf6c-11eb-86b2-397aa77ffe00.jpeg)

**Comment by jpassing** [comment]
> I am facing issue when trying to use Number keys(Num Lock On). But arrow keys are working as expected when Num Lock OFF.

Ok, thanks for confirming! I will take a look.

> And it would be helpful if you fix the default location of scroll as by default it is location down the Scroll bar.

Could you elaborate a bit? I am not sure I understand what you mean.

**Comment by dinesh1844** [comment]
Whenever i open IAP Desktop Thumb in scroll bar (Marked in attached picture) by default it is not in top position in scroll bar. Due to this sometime scroll is not working. I have reopen the application again to fix the scroll issue. This is happening most frequently.

Hope this clarifies the issue.

![WhatsApp Image 2021-06-17 at 1 04 28 PM](https://user-images.githubusercontent.com/81134595/122416110-1ba12b00-cfa6-11eb-96dc-5149f7f15c4c.jpeg)

**Comment by jpassing** [comment]
Regarding numpad: I created #513 to fix the key translations so that they work like `xterm`.

Regarding Project Explorer: When I load a very large project, the scrollbar thumb is indeed not at the top -- just like in your screenshot. However, the scrollbar still worked fine for me -- both when operated by mouse click and by mouse wheel.

Anyway, I created #514 to reduce UI updates and flickering while the tree view is being updated. That fixes the scrollbar thumb positioning issue. I am not 100% sure whether it'll fix the scrollbar-not-working problem that you described.

The fixes will go into the next release.

**Comment by dinesh1844** [comment]
Thanks! And also when we use search bar to search a VM it takes time to load the branches. Hope #514 will fix the issue.

**Comment by jpassing** [comment]
The fix is now available in [release 2.19](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.19.634).

Thanks again for reporting this issue, and please don't hesitate to open new issues if you encounter any other problems with IAP Desktop.
