### ISSUE TITLE
Feature request: portable version

### ISSUE THREAD

**Issue by ivoronin** [GoogleCloudPlatform/iap-desktop#518]
It would be useful to have a portable version of this tool.
Currently, the installer requires admin rights when running on Windows Server (because of https://serverfault.com/questions/580972/why-is-this-preventing-me-installing-an-msi-the-system-administrator-has-set-po).
That makes it troublesome to use it on some bastion and jump hosts.

**Comment by jpassing** [comment]
I agree that the Windows Server group policy issue can be a bit annoying.

The trouble with portable versions is that there's no good way to update them. The current mechanism that checks for new versions every now and then and reminds you to download the latest MSI would not work anymore and chances are that many users would end up running the same version forever. 

Another way to address the issue could be to provide an alternative MSI package that installs per-machine. It would require Admin privileges and place files in `%ProgramFiles%` and should install fine on Windows Server. Do you think that would help?

**Comment by ivoronin** [comment]
1. I've checked auto-update code briefly and have not seen why it won't work for the portable version. It just needs some logic to offer to download a *.zip artifact instead of *.msi one.
2. The main reason for the portable version is the ability to run this tool on Windows Server without requiring admin rights at all.

**Comment by jpassing** [comment]
In the meantime, you can also perform an administrative install to extract the MSI:

```msiexec /A "%USERPROFILE%\Downloads\IapDesktop.msi" TARGETDIR="%APPDATA%" /QB!``` 

This command works fine on Windows Server without admin privileges.

**Comment by jpassing** [comment]
I'm closing this as the benefits of a MSI-based distribution (updating, EULA click-thru, automatic distribution) currently seem to outweigh those of a portable version, and because the is a workaround for installing on Windows Server.

**Comment by taoszhanna** [comment]
The workaround works for me on server 2016 btw
