### ISSUE TITLE
IAP disconnects the VM on selecting Full Screen

### ISSUE THREAD

**Issue by meetvaibhav2009** [GoogleCloudPlatform/iap-desktop#562]
Expected behavior:
* IAP connects to VM
* We select Full Screen using Desktop>Fullscreen
* IAP starts working in Full Screen Mode

Observed behavior:
* IAP connects to VM
* We select Full Screen using Desktop>Fullscreen
* IAP disconnects the VM everytime I have tried with different versions. Earlier I was using 2.21, tried installing 2.11 still the same error.
![image](https://user-images.githubusercontent.com/24803471/134279116-28bd656a-f7f7-49ab-a440-c172df94d7f2.png)

Installed version: 2.11.481.0
.NET Version: 4.8.4300.0
OS Version: Microsoft Windows NT 10.0.19042.0

**Comment by jpassing** [comment]
Unfortunately, there doesn't seem to be a way to avoid this reconnect --  see #245 for details.
