### ISSUE TITLE
IAP Desktop experienced an unrecoverable error

### ISSUE THREAD

**Issue by taoszhanna** [GoogleCloudPlatform/iap-desktop#564]
https://github.com/GoogleCloudPlatform/iap-desktop/blob/08714c0681779892775818349cad77a7d5b13d5f/sources/Google.Solutions.IapDesktop.Extensions.Shell.Test/Google.Solutions.IapDesktop.Extensions.Shell.Test.csproj#L117

The application on several machines repeatedly gets this error and crashes on launch. 
The details link to this particular library: 

System.IO.FileNotFoundException: Could not load file or assembly 'WeifenLuo.WinFormsUI.Docking, Version=3.0.6.0, Culture=neutral, PublicKeyToken=5cded1a1a0a7b481' or one of its dependencies. The system cannot find the file specified.
File name: 'WeifenLuo.WinFormsUI.Docking, Version=3.0.6.0, Culture=neutral, PublicKeyToken=5cded1a1a0a7b481'
at Google.Solutions.IapDesktop.Program.HandleFirstInvocation(String[] args)
at Google.Solutions.IapDesktop.Application.Util.SingletonApplicationBase.Run(String[] args)
at Google.Solutions.IapDesktop.Program.Main(String[] args)
WRN: Assembly binding logging is turned OFF.

**Comment by jpassing** [comment]
I'll close this issue for now. Please re-open if the problem occurs again or if you have any additional logs that could help diagnose it.
