### ISSUE TITLE
Support printer redirection

### ISSUE THREAD

**Issue by AOCGIT** [GoogleCloudPlatform/iap-desktop#572]
Hi, Apologies for any feet stepped on. Has no one brought up the Missing ability to Print? There appears to be ZERO articles stating this Obvious Need and Requirement and Basic function in RDP. 

Is this feature just not possible or has No one ever brought this Requirement up?

There is zero ability to see your Existing Printers, Redirect Your Printers, or Any Attempt to allow printing from the VM back to the 
Device using IAP Desktop.

**Comment by jpassing** [comment]
IAP Desktop currently doesn't support printer (and devide) redirection, because it's primarily intended for server administration. But I agree that it would be a good feature to add, so thanks for the suggestion.

**Comment by jpassing** [comment]
[Version 2.23.722](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.23.722) now lets you (optionally) share local devices, drives, ports, printers, and smart cards.

Thank you for pointing out this feature gap.
