### ISSUE TITLE
Sessions Closed when Going Full Screen

### ISSUE THREAD

**Issue by AOCGIT** [GoogleCloudPlatform/iap-desktop#573]
Is this a Bug or Just no one willing to bring this up. 

When session is established and logged into the VM using IAP Desktop, when going to Enable Full Screen, upon executing Full screen, the "RDP Session" is terminated. Can duplicate this 100% across multiple VMs.

**Comment by jpassing** [comment]
This is a known limitation of the RDP control and unfortunately, there doesn't seem to be a way to avoid this reconnect --  see #245 for details.
