### ISSUE TITLE
System.IndexOutOfRangeException: Buffer does not contain enough data to process request

### ISSUE THREAD

**Issue by Celestica-Edward** [GoogleCloudPlatform/iap-desktop#576]
.NET Framework unhandled exception.

Observed behavior:
* Open a Linux session and run something like htop.
* Exception occurs after a few minutes:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IndexOutOfRangeException: Buffer does not contain enough data to process request
   at VtNetCore.XTermParser.XTermInputBuffer.PeekAhead(Int32 skip)
   at VtNetCore.XTermParser.DataConsumer.Push(Byte[] data)
   at Google.Solutions.IapDesktop.Extensions.Shell.Controls.VirtualTerminal.ReceiveData(String text)
   at Google.Solutions.IapDesktop.Extensions.Shell.Views.SshTerminal.SshTerminalPane.OnDataReceivedFromServerAsync(Object sender, DataReceivedEventArgs args)
   at Google.Solutions.IapDesktop.Extensions.Shell.Views.SshTerminal.SshTerminalPaneViewModel.<>c__DisplayClass38_1.<ConnectAsync>b__6()

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4420.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
IapDesktop
    Assembly Version: 2.21.681.0
    Win32 Version: 2.21.681
    CodeBase: file:///C:/Users/username/AppData/Roaming/Google/IAP%20Desktop/IapDesktop.exe
----------------------------------------
Google.Solutions.IapDesktop.Application
    Assembly Version: 2.21.681.0
    Win32 Version: 2.21.681
    CodeBase: file:///C:/Users/username/AppData/Roaming/Google/IAP%20Desktop/Google.Solutions.IapDesktop.Application.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Google.Solutions.Common
    Assembly Version: 2.21.681.0
    Win32 Version: 2.21.681
    CodeBase: file:///C:/Users/username/AppData/Roaming/Google/IAP%20Desktop/Google.Solutions.Common.DLL
----------------------------------------
Google.Solutions.IapTunneling
    Assembly Version: 2.21.681.0
    Win32 Version: 2.21.681
    CodeBase: file:///C:/Users/username/AppData/Roaming/Google/IAP%20Desktop/Google.Solutions.IapTunneling.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Google.Solutions.Ssh
    Assembly Version: 2.21.681.0
    Win32 Version: 2.21.681
    CodeBase: file:///C:/Users/username/AppData/Roaming/Google/IAP%20Desktop/Google.Solutions.Ssh.DLL
----------------------------------------
Google.Apis.Core
    Assembly Version: 1.52.0.0
    Win32 Version: 1.52.0.0
    CodeBase: file:///C:/Users/username/AppData/Roaming/Google/IAP%20Desktop/Google.Apis.Core.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 3.0.6.0
    Win32 Version: 3.0.6.0
    CodeBase: file:///C:/Users/username/AppData/Roaming/Google/IAP%20Desktop/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2015
    Assembly Version: 3.0.6.0
    Win32 Version: 3.0.6.0
    CodeBase: file:///C:/Users/username/AppData/Roaming/Google/IAP%20Desktop/WeifenLuo.WinFormsUI.Docking.ThemeVS2015.DLL
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4261.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4420.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Google.Solutions.IapDesktop.Extensions.Activity
    Assembly Version: 2.21.681.0
    Win32 Version: 2.21.681
    CodeBase: file:///C:/Users/username/AppData/Roaming/Google/IAP%20Desktop/Google.Solutions.IapDesktop.Extensions.Activity.DLL
----------------------------------------
Google.Apis.Compute.v1
    Assembly Version: 1.52.0.0
    Win32 Version: 1.52.0.0
    CodeBase: file:///C:/Users/username/AppData/Roaming/Google/IAP%20Desktop/Google.Apis.Compute.v1.DLL
----------------------------------------
Google.Apis
    Assembly Version: 1.52.0.0
    Win32 Version: 1.52.0.0
    CodeBase: file:///C:/Users/username/AppData/Roaming/Google/IAP%20Desktop/Google.Apis.DLL
----------------------------------------
Google.Apis.Storage.v1
    Assembly Version: 1.52.0.2234
    Win32 Version: 1.52.0.2234
    CodeBase: file:///C:/Users/username/AppData/Roaming/Google/IAP%20Desktop/Google.Apis.Storage.v1.DLL
----------------------------------------
Google.Apis.Logging.v2
    Assembly Version: 1.52.0.2367
    Win32 Version: 1.52.0.2367
    CodeBase: file:///C:/Users/username/AppData/Roaming/Google/IAP%20Desktop/Google.Apis.Logging.v2.DLL
----------------------------------------
Google.Solutions.IapDesktop.Extensions.Os
    Assembly Version: 2.21.681.0
    Win32 Version: 2.21.681
    CodeBase: file:///C:/Users/username/AppData/Roaming/Google/IAP%20Desktop/Google.Solutions.IapDesktop.Extensions.Os.DLL
----------------------------------------
Google.Solutions.IapDesktop.Extensions.Shell
    Assembly Version: 2.21.681.0
    Win32 Version: 2.21.681
    CodeBase: file:///C:/Users/username/AppData/Roaming/Google/IAP%20Desktop/Google.Solutions.IapDesktop.Extensions.Shell.DLL
----------------------------------------
AxInterop.MSTSCLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/username/AppData/Roaming/Google/IAP%20Desktop/AxInterop.MSTSCLib.DLL
----------------------------------------
Interop.MSTSCLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/username/AppData/Roaming/Google/IAP%20Desktop/Interop.MSTSCLib.DLL
----------------------------------------
Google.Apis.CloudOSLogin.v1
    Assembly Version: 1.52.0.2279
    Win32 Version: 1.52.0.2279
    CodeBase: file:///C:/Users/username/AppData/Roaming/Google/IAP%20Desktop/Google.Apis.CloudOSLogin.v1.DLL
----------------------------------------
Google.Apis.Auth
    Assembly Version: 1.52.0.0
    Win32 Version: 1.52.0.0
    CodeBase: file:///C:/Users/username/AppData/Roaming/Google/IAP%20Desktop/Google.Apis.Auth.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.1.25517
    CodeBase: file:///C:/Users/username/AppData/Roaming/Google/IAP%20Desktop/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Google.Apis.CloudResourceManager.v1
    Assembly Version: 1.52.0.2281
    Win32 Version: 1.52.0.2281
    CodeBase: file:///C:/Users/username/AppData/Roaming/Google/IAP%20Desktop/Google.Apis.CloudResourceManager.v1.DLL
----------------------------------------
vtnetcore
    Assembly Version: 1.0.30.19
    Win32 Version: 1.0.30.19
    CodeBase: file:///C:/Users/username/AppData/Roaming/Google/IAP%20Desktop/vtnetcore.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

Installed version: 2.21.681.0
.NET Version: 4.8.4420.0
OS Version: Microsoft Windows NT 10.0.19043.0

**Comment by jpassing** [comment]
This looks similar to #545 -- I guess there's some byte sequence that trips up the vtnetcore parser. 

I tried to reproduce it by running `htop`, but I don't get the error.

It would be super helpful if you could capture and share some of the received data:

1. Enable logging (Tools > Enable logging)
2. Reproduce the error, then click **Continue**
3. Hold the **Shift** key while right-clicking the tab of the SSH session
4. Select **Copy received data**
5. Disable logging (Tools > Enable logging)
6. Paste the copied data into a text file

The culprit should be close to the end of the capture, so it's probably enough to share the last few pages, You can send the text file to iap-desktop at google.com to avoid sharing it publicly.

**Comment by Celestica-Edward** [comment]
Thanks, I have emailed the logs over.

**Comment by jpassing** [comment]
Thanks for sending the logs. Although the logs weren't quite sufficient to reproduce the error, I have an idea of what might have happened.

If you have the time, it would be great if you could give the attached version a try. It's the latest build of the `master` branch, slightly ahead of the 2.22 release. This version:

* has improved error handling for the xterm parser -- if it encounters specific invalid or incomplete escape sequence, it shouldn't show this IndexOutOfRange error anymore.
* has improved logging; the logs now include the `vtnetcore` logs.

With that version, it would be great if you could run `htop` again with logging enabled, and share the log file again (only the log, not the received data). 


[IapDesktop-2.22.711-x86-Release.msi.zip](https://github.com/GoogleCloudPlatform/iap-desktop/files/7735590/IapDesktop-2.22.711-x86-Release.msi.zip)

**Comment by Celestica-Edward** [comment]
Hi,

I tried the new version and let it run for 10 minutes and it worked fine. Attached is the log.

[2021-12-17_0935.zip](https://github.com/GoogleCloudPlatform/iap-desktop/files/7735845/2021-12-17_0935.zip)
.

**Comment by jpassing** [comment]
Great, thanks for verifying! The logs looks okay too.

I'll keep the issue open for now and close it once 2.23 is released.

**Comment by jpassing** [comment]
[Version 2.23.722](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.23.722) now includes the fix. Thanks for reporting this issue and helping me fix it!
