### ISSUE TITLE
Is there a way to pass Windows keyboard shortcuts to the remote VM without going full screen?

### ISSUE THREAD

**Issue by shawn-orange** [GoogleCloudPlatform/iap-desktop#607]
Absolutely loving IAP Desktop, thank you!

Is there a setting somewhere I've missed that will pass the Windows key and all Windows shortcuts (Win-R for run, Win-E for Explorer, etc) to the remote VM even if it's not full screen?  Most other RDP front ends I've used allow that, though it's usually full-screen only by default.

**Comment by jpassing** [comment]
Yes, in windowed mode, some of the standard Windows shortcuts don't work. There are replacement shortcuts for the most important ones (see **Desktop > Keyboard shortcuts**), but that doesn't include `Win+E` or `Win+R`.

The RDP control seems to have [a setting](https://docs.microsoft.com/en-us/windows/win32/termserv/imsrdpclientadvancedsettings-enablewindowskey) to enable the Windows key. Maybe it's an option to expose that setting in IAP Desktop, I'll look into that.

**Comment by shawn-orange** [comment]
Wonderful, thank you!

**Comment by jpassing** [comment]
[Version 2.24.735](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.24.735) now lets you control whether Windows keyboard shortcuts should be handled locally or passed to the remote VM. 

Thank you for suggesting this feature.

**Comment by SavantAskew** [comment]
Good day, and thank you for the feature to allow control over whether the host or remote machine is sent the Windows key. Could I by any chance ask you how to enable this feature?

All the best!

**Comment by shawn-orange** [comment]
> Good day, and thank you for the feature to allow control over whether the host or remote machine is sent the Windows key. Could I by any chance ask you how to enable this feature?

Depending on how granular you want to get, go into Connection Settings at the VM level, zone level, or project level.  Change the setting "Enable Windows shortcuts" to whatever you want it to be.  I have it set to "Always" for all of my projects and it's been great!
