### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by rm185271** [GoogleCloudPlatform/iap-desktop#631]
Steps:
* Step 1 - Click on server to connect  and get the error screen "Connecting to VM instance failed" "Object already exists"

Expected behavior:  To make server connection
Observed behavior:  Get the error screen "Connecting to VM instance failed" "Object already exists"

```

Installed version: 2.25.755.0
.NET Version: 4.8.4480.0
OS Version: Microsoft Windows NT 10.0.18363.0
```

**Comment by jpassing** [comment]
Do you get the same error for all VMs, or just a specific one? And is that a Linux or Windows VM?

To diagnose the issue, it would be helpful if you could share the log:
1. Select **Tools > Enable logging** to enable logging
1. Reproduce the error
1. Select **Tools > Enable logging** to disable logging and flush the log (or close the application)
1. Find the log file in `%appdata%\Google\IAP Desktop\Logs` 

You can attach the log file here or (better) send it to iap-desktop@google.com.

**Comment by rm185271** [comment]
Hi

Email sent with logs attached...

Do you get the same error for all VMs, or just a specific one? And is that a Linux or Windows VM? Yes

**Comment by jpassing** [comment]
Thanks for sharing the log.

What's odd is that the log looks like it comes from version 2.22 or earlier, but the bug description says you're using 2.25. I wonder if your installation has some mish-mash of different versions, which might explain the issue. 

Could you open a command prompt (non-elevated) and run

``` 
msiexec /fa {9987D32C-3306-45C3-8548-3A775C68A298}
``` 

That should re-install all files from the 2.25 package. After that, check if the problem persists.


That GUID is the product code of IAP Desktop 2.25. If the command fails, then you don't have 2.25 installed after all, and it might be best to upgrade to that version first.




If the problem persists, then I suggest you manually delete the SSH keys used by IAP Desktop. 

You can list existing keys by running:

```
certutil -csp "Microsoft Software Key Storage Provider" -key -user | findstr IAPDESKTOP_
```

You should see at least one key named `IAPDESKTOP_<your-email-address>`, that's the RSA3076 key used for SSH auth.

Delete the key by running

```
certutil -csp "Microsoft Software Key Storage Provider" -user -delkey IAPDESKTOP_<your-email-address>
```

for each key. Note that deleting the is generally safe -- IAP Desktop will just create a new key and publish it to OS Login/project/instance metadata the next time you connect.

Then try connecting to Linux VM _twice_ and see if the issue goes away.



Is your workstation joined to a domain and uses roaming user profiles? Although that shouldn't be an issue, it might explain such inconsistencies.

**Comment by rm185271** [comment]
Sorry I panicked and uninstalled 2.25 thinking it was the version and reinstalled older version I had originally installed.

Per instructions below I reinstalled version 2.25.
![image](https://user-images.githubusercontent.com/78031502/160843847-2dd15ac3-df42-4251-b984-5ef6777f1de4.png)

The problem still persisted.
![image](https://user-images.githubusercontent.com/78031502/160843913-f408c19a-4fca-4fa1-a43e-d9519ed68c2a.png)

List existing keys and ran delete
![image](https://user-images.githubusercontent.com/78031502/160843946-cbfc0976-5708-484a-bbc6-80ce12123857.png)

Tried connecting to Linux VM twice, problem still exist…
![image](https://user-images.githubusercontent.com/78031502/160843997-855e6608-cdde-44a2-9cf8-6b40340c1295.png)

Logs attached
[2022-03-30_0915.log](https://github.com/GoogleCloudPlatform/iap-desktop/files/8380803/2022-03-30_0915.log)
…

**Comment by jpassing** [comment]
Thanks for the quick reply.

Interestingly, all your `certutil` commands failed with `NTE_BAD_KEYSET`, indicating that the key couldn't be loaded properly. That's the exact same problem IAP Desktop encounters, causing the "Object already exists" message.

So it seems that there's something going on with the key container, or the way it's configured -- it might have nothing to do with IAP Desktop itself.

If you run `certutil -csp "Microsoft Software Key Storage Provider" -key -user` (without the `findstr`), does it list other keys properly, or is it showing the same `NTE_BAD_KEYSET` error for every single key?

**Comment by rm185271** [comment]
Hi

Output from certutil -csp "Microsoft Software Key Storage Provider" -key -user

![image](https://user-images.githubusercontent.com/78031502/160862011-dd83e749-42ab-40ce-9906-e546ef7df72e.png)

**Comment by jpassing** [comment]
Interesting... only 1 of the 5 keys could be opened -- and the only one that works is an ECDSA key. Is it possible that your machine is configured to _not_ allow RSA encryption?

IAP Desktop uses RSA by default, but you can change it to ECDSA:

1. Open IAP Desktop.
2. Go to **Tools > Options > SSH** and change **key type** to `ECDSA NIST P-256`. Apply changes.
3. Try connecting to a VM again. IAP Desktop should now generate a new ECDSA key and use that for SSH auth.
4. Run `certutil -csp "Microsoft Software Key Storage Provider" -key -user`  once more. 
 
Does that work? And does the ECDSA key show up properly in the `certutil` output?

**Comment by jpassing** [comment]
Great to hear that it works now.

As the issue was caused by Windows, I'm not sure if there's any way to prevent this issue in IAP Desktop. But the error message clearly wasn't very helpful, so I'll fix that.
