### ISSUE TITLE
File upload download option

### ISSUE THREAD

**Issue by ahmedulde7** [GoogleCloudPlatform/iap-desktop#633]
Option to upload files and download files from the GUI like we have on the GCP console

**Comment by jpassing** [comment]
I assume you're referring to Linux/SSH connections? For Windows/RDP, you can copy/paste files... but for Linux, I agree that some way of transferring files would be useful.

**Comment by jpassing** [comment]
[Version 2.27](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.27.810) now supports uploading files by dragging and dropping them onto an SSH terminal. 

You can expect future versions to expand on that feature and also support download.

**Comment by dinesh1844** [comment]
Upload option to linux vm is helpful. We also require the download feature. Is there any plan in pipeline for expanding the scp feature for download. It would be much helpful.

**Comment by jpassing** [comment]
Yes, still planning to add download support as well.

What I'm not quite sure about yet is the UX: Should the app just prompt users to enter a file path? That would arguably the easiest way to implement the feature, but it also wouldn't be very convenient. I guess some kind of file picker would be more appropriate (like Cloud Shell added recently).

**Comment by dinesh1844** [comment]
File picker would be more appropriate as you said. For initial version it would helpful if it is just prompt where user can provide a path to download.

**Comment by jpassing** [comment]
This feature will land in the next release and will include a remote file picker:

![image](https://user-images.githubusercontent.com/5724941/198920360-de1de3ab-ae8f-4d93-aa8b-90d87b9e5740.png)

**Comment by dinesh1844** [comment]
Thanks! Any ETA for the new release? If it will be delayed is it possible to provide a beta release for me?

**Comment by jpassing** [comment]
Just released version [2.33.964](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.33.964).

I'm closing this issue now. If you encounter any issues with SFTP file downloads, or have other feature suggestions, please don't hesitate to open new issues.
