### ISSUE TITLE
Adding an account doesn't work

### ISSUE THREAD

**Issue by MsternSC** [GoogleCloudPlatform/iap-desktop#678]
Hi, when clicking the plus sign on the bottom right to add a new account, nothing happens

**Comment by jpassing** [comment]
Sorry for the late response.

Which plus sign are you referring to? If you're looking for a way to switch between multiple user accounts, then that's currently not possible. But there is an existing FR (#600) for adding that capability, and I plan try to implement that in one of the next versions.

**Comment by MsternSC** [comment]
![image](https://user-images.githubusercontent.com/101726160/171630475-1a7e2ae5-859c-4116-9058-eeb0a1697461.png)
That would be this

**Comment by jpassing** [comment]
Interesting -- it should be an 'x', not a '+':
![image](https://user-images.githubusercontent.com/5724941/171771876-a1f2d510-dfa0-4766-a56b-bb78e5acc31d.png)

It's code point U+2716 (HEAVY MULTIPLICATION). This seems to be [an issue with Windows 11](https://stackoverflow.com/questions/70852173/u2716-character-displaying-incorrectly-in-chrome-97-on-windows-11).

**Comment by MsternSC** [comment]
Oh, that's very interesting, thanks anyway

**Comment by jpassing** [comment]
[Version 2.28](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.28.827) now lets you add and switch between multiple profiles. The user fly-out window is now gone.

The `x` vs `+` issue still applies to the endpoint verification fly-out window, but that's not shown unless you've enabled endpoint verification and I hope that Windows 11 will fix the font issue at some time. So I don't think that's worth fixing for now.
