### ISSUE TITLE
Power On | Power Off | Restart VM - enhancement request

### ISSUE THREAD

**Issue by aeolius** [GoogleCloudPlatform/iap-desktop#679]
Would it be possible to add a few options to the VM context menu in addition to 'Connect' such as Power On | Power Off | Restart?

**Comment by jpassing** [comment]
Yes, that seems like a useful feature and shouldn't be a problem.

**Comment by jpassing** [comment]
[The latest release (2.31.901)](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.31.901) now includes this feature: You can start/stop/suspend/resume VMs from within the context menu in the Project Explorer window.

![image](https://user-images.githubusercontent.com/5724941/188058801-114134f3-8393-4288-ab5a-e0a33c6b175c.png)

Thanks again for suggesting this feature.
