### ISSUE TITLE
Intermittent connectivity issue while accessing VM

### ISSUE THREAD

**Issue by dinesh1844** [GoogleCloudPlatform/iap-desktop#701]
Facing the below error while accessing the VM. When i re-try it is successful on 3rd or 4th attempt. Sometime the project loading is also failing re-try work for the same. I am not sure whether it the issue on my side or not. I am accessing IAP Desktop on citrix VDI.

![WhatsApp Image 2022-06-23 at 3 12 56 AM](https://user-images.githubusercontent.com/81134595/175144766-165ca8d8-2199-48b3-830d-e331ea12e018.jpeg)

**Comment by jpassing** [comment]
Closing issue as per email conversation.
