### ISSUE TITLE
Permission error when connecting to a GCP VM through IAP Desktop

### ISSUE THREAD

**Issue by guidodl** [GoogleCloudPlatform/iap-desktop#702]
Hi all,

I am facing permission error when i am trying to connect to a VM with IAP Desktop.
I have the following roles in the project:

- Cloud SQL Instance User
- Compute OS Login
- IAP-secured Tunnel User
- Kubernetes Engine Viewer
- Logs Viewer
- OS Login Project Get Role
- Source Repository Writer

Google.Solutions.IapDesktop.Application Verbose: 0 : Enter ShowErrorDialogWithHelp(Connection terminated, You do not have sufficient permissions to access this VM instance.

To perform this action, you need the following roles (or an equivalent custom role):

 1. 'Compute OS Login' or 'Compute OS Admin Login'
 2. 'Service Account User' (if the VM uses a service account)
 3. 'Compute OS Login External User' (if the VM belongs to a different GCP organization
, SshNativeException:
Username/PublicKey combination invalid
)

I attach the log's file with the full error.

[2022-06-24_1224.log](https://github.com/GoogleCloudPlatform/iap-desktop/files/8975486/2022-06-24_1224.log)
Thank you,
Guido

**Comment by jpassing** [comment]
Does the VM have an attached service account? Then you'll need the _Service Account User_ role as well.

Another possible reason is that the VM doesn't permit public key authentication using `rsa-ssh`. In that case, switching to `ECDSA` (in **Tools > Options > SSH**) should fix the issue.

**Comment by guidodl** [comment]
Hi @jpassing,

I’ve added Service Account User role to the user and now it works! 

Thank you for the help,
Guido.
