### ISSUE TITLE
IAP-desktop ( windows ) - Icons not appearing 

### ISSUE THREAD

**Issue by DanyLan** [GoogleCloudPlatform/iap-desktop#706]
Issue:  Windows Icon will not appear so I cannot right click and connect. Linux instances will populate but not windows

Troubleshooting: 
1 Linux vms icons do appear and I can use IAP desktop to connect. I am not able to have the windows ones to populate.
2 I know that the tests I have been doing on different Windows machines are working as my colleagues can use IAP desktop and do see the windows icon and can log in. Multiple windows versions on different projects IDs were tested and i was not able to fix my issue for Windows.
3 Next, i uninstall IAP desktop, reinstall but same issue.
4 My colleagues and I have the same version of IAP desktop
5 The only difference is my local machine [1]. My colleagues are on windows 10.
6 Other things I have tried; unload project/reload, sign out/sign back in.

Anyone else experiencing the same issue? Or did i miss a troubleshooting step? Thanks.

[1]Edition	Windows 11 Pro
Version	21H2
Installed on	‎2/‎1/‎2022
OS build	22000.739
Experience	Windows Feature Experience Pack 1000.22000.739.0

------------
My IAP desktop version

2.28.827.0
.net 4.8.4515.0

**Comment by jpassing** [comment]
Cf. https://issuetracker.google.com/issues/237920104
