### ISSUE TITLE
Enhancement request: Improve "Float" window mode 

### ISSUE THREAD

**Issue by rmatte** [GoogleCloudPlatform/iap-desktop#712]
When setting an ssh or rdp tab to the "Float" mode it would be nice if it would become it's own window (selectable on the taskbar) with maximize/minimize controls.  Currently it doesn't and as soon as you go to maximize it by double clicking on the title bar it snaps right back in to the main window.  It's awkward to work with.

I'd recommend switching out the "float" mode option to an "unsnap tab" type feature and having each unsnapped tab as it's own window with it's own controls.

I'm loving this app and I'm sure this is something that a lot of google cloud users want (to be able to have their ssh and rdp sessions through iap via an actual desktop app) but this is a pretty severe usability pain point with it at the moment.

As an aside, it would be great if this project were given more development resources.  I didn't even realize this existed until today, this would be something excellent to advertise in the google cloud web console as being an access option once the software is a bit more mature and the installation on macos and linux is simplified.

**Comment by jpassing** [comment]
Thanks for your feedback and this feature suggestion!

> I'd recommend switching out the "float" mode option to an "unsnap tab" type feature and having each unsnapped tab as it's own window with it's own controls.

If I understand your idea correctly, then the separate window would...
* have the usual minimize/maximize/close window controls
* show up in the task bar
* host one or more tabs/sessions
* _not_ have a menu (unlike the main window)
* close automatically if you close the main window

That's pretty much how modern Visual Studio versions behave when you "tear off" a document, so I think that would make sense. I'll have to check whether the underlying library supports this kind of windowing behavior.

**Comment by rmatte** [comment]
That's exactly right.

**Comment by jpassing** [comment]
This feature is now available in [release 2.32](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.32.939). Thanks again for the suggestion.
