### ISSUE TITLE
Enhancement request: inherit windows color theme or add a dark window mode/theme

### ISSUE THREAD

**Issue by rmatte** [GoogleCloudPlatform/iap-desktop#715]
It would be nice if the app would inherit from the windows color theme and color itself accordingly.  Or at least have a dark mode that can be enabled (which might be easier to do).  I'm currently using a dark theme in windows and the iap desktop app stays bright white so it looks out of place.  If it even just had a dark theme that I could toggle on it would be great.

**Comment by jpassing** [comment]
It took a while, but [release 2.35](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.35.1020) now supports dark mode:

![image](https://user-images.githubusercontent.com/5724941/224195151-74514455-a521-40b1-b541-1bd03139d2a8.png)

You can choose between the (default) light theme and a new dark theme by going to **Tools > Options > Appearance**.
