### ISSUE TITLE
Enhancement request: duplicate tab option

### ISSUE THREAD

**Issue by rmatte** [GoogleCloudPlatform/iap-desktop#716]
It would be nice to be able to right click on a tab and have a "duplicate" option there to open another session in a new tab on the same vm.

**Comment by jpassing** [comment]
Yes, I agree that would be a useful feature for SSH.

For RDP, it might make less sense because of the RDP session limits imposed by Windows/Windows Server.

**Comment by rmatte** [comment]
Right, I was thinking of this in the context of ssh. Thanks.

**Comment by jpassing** [comment]
[IAP Desktop 2.30](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.30.878) now lets you duplicate SSH sessions:

![image](https://user-images.githubusercontent.com/5724941/183796271-2eaa9843-4397-47eb-9e75-72b568138516.png)

The context menu is now equivalent to the **Session** main menu.

Thanks for suggesting this feature.
