### ISSUE TITLE
Port settings not updating after applied for the whole project / zone

### ISSUE THREAD

**Issue by MsternSC** [GoogleCloudPlatform/iap-desktop#724]
Hi, I changed the port on a specific VM and it's not updating because I already used a different port for the project.

**Comment by jpassing** [comment]
Right, if you specify a non-default value at the zone or project level, then you can't reset the value to its default at the VM level. A fix is on its way.

**Comment by jpassing** [comment]
The [latest release](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.29.851) now contains a fix for this.

Thanks for reporting this issue!
