### ISSUE TITLE
feature request: support password based login for linux

### ISSUE THREAD

**Issue by macdonch** [GoogleCloudPlatform/iap-desktop#743]
I have some VMs that are using and external ldap provider for login, rather than SSH keys. It would be nice if we could have a setting to allow password based login after establishing the IAP tunnel, instead of expecting keys.

**Comment by jpassing** [comment]
Thanks for the suggestion.

I suppose you'd want IAP Desktop to store the username and password like it does for Windows?

**Comment by macdonch** [comment]
Yes, I think it would make sense to have it be similar to how you can deal with credentials for rdp, i.e. either store them or not.

**Comment by jpassing** [comment]
This feature [is now available in version 2.39](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.39.1348)..
