### ISSUE TITLE
Ability to export and import projects in bulk

### ISSUE THREAD

**Issue by kumaRITC** [GoogleCloudPlatform/iap-desktop#748]
Ability to export and import projects in bulk

IAP desktop lacks this very basic feature.

**Comment by jpassing** [comment]
Thanks for suggesting this feature.

Just to clarify: If the **Add project** dialog allowed selecting multiple projects at once, would that solve the issue? Or do you have some other UI in mind?

**Comment by kumaRITC** [comment]
Hi Johannes,

Thank You for quick reply.   Selecting multiple projects can certainly help.
Ctrl+A  to select all and then unselect  any unwated items in the displayed list

also it would help greatly if the Add project dialog can read list of projects from a  ascii txt file

**Comment by kumaRITC** [comment]
Also similar to Add Project  we need Remove Project dialog.  Thanks

**Comment by jpassing** [comment]
That makes sense, thanks for clarifying.

**Comment by jpassing** [comment]
[The latest release (2.31.901)](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.31.901) now includes this feature: When adding or unloading projects, you can select multiple projects at once (or use Ctrl+A to select all).

Thanks again for suggesting this feature.

**Comment by kumaRITC** [comment]
Thank You ...so much ...  this is so helpful


*Kumar Dammu*
*RISHABH CORPORATION *
Cloud Services Provider
9631 Turtle Landing Ct, Orlando, FL 32832
*+19088347961*
*rishabh.cloud*
<https://twitter.com/RishabhCloud22>
<https://www.linkedin.com/in/rishabh-infotech-corporation-62581719a>
   [image:
@Skype] <https://join.skype.com/invite/To8ROTkzTWKx>
