### ISSUE TITLE
Tools > Options produces an exception 2.31.901.0

### ISSUE THREAD

**Issue by damionwilliams** [GoogleCloudPlatform/iap-desktop#773]
Fantastic update for the power on/off VMS. Thanks!

A minor issue is that it looks like accessing Tools>Options may have broken in 
2.31.901.0
.NET 4.8.4515.0

----
[Window Title]
An error occured

[Main Instruction]
Opening Options window failed

[Content]
IExceptionDialog

**Comment by jpassing** [comment]
> A minor issue is that it looks like accessing Tools>Options may have broken

Thanks for reporting this so quickly... that's a very embarrassing bug. I'll prepare a fix for that today.

**Comment by jpassing** [comment]
Release [2.31.905](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.31.905) now contains a fix for this issue.
