### ISSUE TITLE
Auto-Collapse Project Tree View when starting?

### ISSUE THREAD

**Issue by jlempka-managecore** [GoogleCloudPlatform/iap-desktop#775]
Is there currently a way to automatically collapse the project tree view when starting?  Would it be possible to add that as a configurable option?  Or possibly auto-save the current tree view upon program close and restore upon program start?

Thank you.

**Comment by jpassing** [comment]
Thanks for your feedback. To clarify -- is this primarily about...
* speeding up startup (i.e. the current behavior of auto-expanding all projects takes too long), or 
* keeping things organized (i.e., you have many projects, but typically only work in one project at a time, so having everything expanded is unnecessary distraction)?

Currently, IAP Desktop auto-expands all projects. It would be possible to change that behavior, but I'd like to make sure I understand the motivation properly.

Johannes

**Comment by jlempka-managecore** [comment]
Hi Johannes,

In this scenario, the use case is the second - keeping things organized.  In our environment, we're a managed service provider and it's not uncommon to have many projects loaded into IAP Desktop (I currently have 20 projects loaded across multiple customers) but frequently focusing on only one or two depending on customer workload.

The first use case - speeding startup - was addressed with past changes to load projects in parallel and in background and we have no complaints on the speed of startup.

Thank you,
Jason

**Comment by jpassing** [comment]
That makes sense, thank you for clarifying.

**Comment by jpassing** [comment]
This feature is now available in [release 2.32](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.32.939). Thanks again for the suggestion!
