### ISSUE TITLE
SFTP - Default user

### ISSUE THREAD

**Issue by dinesh1844** [GoogleCloudPlatform/iap-desktop#829]
While using sftp download the download session uses the user which is used for authentication of IAP Desktop. Is it possible to use the current session user if we have used switch user command?

**Comment by jpassing** [comment]
Unfortunately, SFTP doesn't really support `sudo`: There is [a trick to make it work](https://serverfault.com/questions/336540/how-to-change-user-to-root-in-an-sftp-client), but that's [currently not supported by `libssh2`](https://github.com/libssh2/libssh2/issues/644), which is the SSH implementation that IAP Desktop uses. 

So I don't think it's currently possible to add this feature.
