### ISSUE TITLE
Authentication error when trying to connect to a VM (issue #279 reopened)

### ISSUE THREAD

**Issue by k-byun** [GoogleCloudPlatform/iap-desktop#854]
Similar issue to #279

I'm facing the same issue, as reported from one of the user.

![image](https://user-images.githubusercontent.com/72177353/208964378-3c797215-c890-4570-8b5b-d03e6a72cf93.png)

We've tested the IAP on 2 admin accounts and 1 non-admin accounts, which all worked well flawless.  We started rolling out the use of the tool, and an user with non-admin privileges has reported the error shown above.

Was there any fix/resolution on the issue that was closed?

**Comment by k-byun** [comment]
My version being used on frrqn73: 
Version 2.33.964.0
.NET 4.8.9105.0

Author: Johannes Passing

**Comment by jpassing** [comment]
If I understand correctly, this error occurs on one user's computer while IAP Desktop works fine on other user's computers. Is that correct? 

And on the affected user's computer, does the error occur for _any_ VM they try to connect to, or only a specific VM?

I'd suggest to try the following on the affected computer: 
1. In the **Connection settings** for the VM, check if the username is prefixed with `.\` (for ex, `.\myuser`). If not, add the `.\`.
2. Try connecting again.

If that doesn't work, try to:

1. Right-click the VM and select **Connect as user**.
2. Enter credentials manually (again, make sure you prefix your username with `.\`).

If none of that works, I have a few more questions:

1. Is the affected user's computer domain-joined? 
2. Is the VM domain-joined?

**Comment by k-byun** [comment]
Yes on the first question: the error only occurs on one particular user's computer. 

I've got only one vm set up to use iap tunnel but I can set another up to see if the issue happens only on one vm or on all for the particular user. 

I've actually suggested the user to prefix the username with ".\" a few hours ago (I'll post his response when I hear back).

"Connect as user" was suggested already but login still failed, producing the same error message. 

Affected user's computer is domain joined(I'll double check this in 12 hrs), but the vm is not domain joined.

**Comment by jpassing** [comment]
Thanks for the update. Have you also had a chance yet to test if adding the `.\` prefix makes any difference?

**Comment by jpassing** [comment]
Ok, thanks for confirming that it applies to multiple VMs, but only one user.

It might be worth checking if the user has any saved RDP credentials that could interfere here. You can find the saved credentials under **Control Panel > User Accounts > Credential Manager > Windows Credentials** (or by running `cmdkey /list`). If there is a saved credential for `TERMSRV\localhost`, delete it and see if that makes a difference.

In #279, the issue seems to have been related to local credential storage (in Windows itself, not IAP Desktop), so resetting the password helped (on the client, not the VM). Maybe that's another thing worth trying?

**Comment by k-byun** [comment]
Thank you, and I appreciate for suggested solution. I will have the user try it out and report back the response here.

**Comment by jpassing** [comment]
I'm closing this issue as I haven't heard back from you. Please reopen if the problem perists/reappears.
