### ISSUE TITLE
Feature request: Bypass/disable IAP for specific instances

### ISSUE THREAD

**Issue by ixniz** [GoogleCloudPlatform/iap-desktop#870]
I would like the option to turn off or bypass IAP for specific connections or projects where IAP access has not been enabled for some reason (API not enabled or Firewall not allowing IAP - but for instance allowing regular RDP). This could be either an instance specific setting or perhaps even a project level setting in the client. 

I currently have a mix of projects where some allows IAP access and others do not so this is mainly a QoL feature request where I could still use IAP Desktop for all my GCP RDP needs, without having to switch to a different client for some instances.

**Comment by jpassing** [comment]
Thanks for this feature suggestion.

How do you currently connect to these non-IAP VMs -- using (a) their private IP address over VPN/Interconnect, or (b) using their public IP address over the internet?

Adding support for (a) seems reasonable to me, and I'd expect that others would benefit from that as well. I'd be a bit skeptical about (b) though: Exposing RDP over the public internet is pretty risky, and I'm not sure if it's a good idea to make it _easier_ to follow this practice...

**Comment by jpassing** [comment]
Sounds good. We can make that a connection setting so that you can control it by instance or project.

**Comment by jpassing** [comment]
This feature is now available in [release 2.36](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.36.1101): If you set **Connect via** to **Vpc** in the connection settings, IAP Desktop will directly connect to the VM's private IP address:

![image](https://github.com/GoogleCloudPlatform/iap-desktop/assets/5724941/37ea6011-222e-4d97-99dc-9fdb1af9c8d9)

Thanks again for suggesting this feature.

**Comment by ixniz** [comment]
Thanks for implementing it! :)
