### ISSUE TITLE
Allow HTTP traffic of IAP proxy pass through (corporate) proxy

### ISSUE THREAD

**Issue by maestrx** [GoogleCloudPlatform/iap-desktop#990]
Hello,

would it be possible to have a possibility to have all IAP flows going through HTTP proxy before hitting GCP endpoints? We cannot use it till then...

Thanks

**Comment by jpassing** [comment]
If you've configured Windows to use a HTTP proxy, then IAP Desktop will automatically use that. Alternatively, you can also configure proxy settings in IAP Desktop under **Tools > Options > Network**. The proxy is used for all HTTPS communication, including IAP TCP forwarding.

Is this not working for you? Or am I misunderstanding your question?

**Comment by jpassing** [comment]
I assume my previous reply resolved the question? If not, please reopen the issue.
